export const defaultProps = {
  cancelLabel: "Cancel",
  saveLabel: "Save",
  saveInProgressLabel: "Saving...",
  savePendingLabel: "Validating...",
  submitFeedbackDelay: 100,
  itemLabelPosition: "top",
  itemLabelBreak: true,
  keepModalOpenOnSubmit: false,
  swapCancelAndSave: false,
  hideButtonRowUntilDirty: false,
  hideButtonRow: false,
  stickyButtonRow: false,
  enableSubmit: true,
  itemRequireLabelMode: "markRequired" as const,
  validationIconSuccess: "checkmark",
  validationIconError: "error",
  keepOnCancel: false,
  dataAfterSubmit: "keep" as const,
  submitPolicy: "single-flight" as const,
};
