export const defaultProps = {
  enabled: true,
  validationStatus: "none" as const,
  mode: "single" as const,
  dateFormat: "MM/dd/yyyy" as const,
  showWeekNumber: false,
  weekStartsOn: 0,
  inline: true,
  clearable: false,
  clearToInitialValue: false,
  required: false,
  labelPosition: "top",
  readOnly: false,
  autoFocus: false,
  labelBreak: false,
  emptyCharacter: "-",
};
