import type { XmluiComponentContract } from "./types";
import { supportedLayoutPropNames } from "../../styling";
import { htmlTagDefinitions } from "../../component-core/htmlTags";
import { htmlTagMetadata } from "../../components/HtmlTags/HtmlTags";
import { BrCapitalizedMd, BrMd } from "../../components/Br/Br";
import { FragmentMd } from "../../components/Fragment/Fragment";
import { ImageMd } from "../../components/Image/Image";
import { IFrameMd } from "../../components/IFrame/IFrame";
import { contractFromMetadata } from "./fromMetadata";

export const builtInComponentContracts: XmluiComponentContract[] = [
  ...htmlTagDefinitions.map((definition) =>
    contractFromMetadata(htmlTagMetadata[definition.name], {
      name: definition.name,
      acceptsArbitraryProps: true,
      includeLayoutProps: true,
    }),
  ),
  contractFromMetadata(BrMd, {
    name: "br",
    allowsChildren: false,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
  }),
  contractFromMetadata(BrCapitalizedMd, {
    name: "Br",
    allowsChildren: false,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
  }),
  contractFromMetadata(FragmentMd, {
    name: "Fragment",
    includeLayoutProps: false,
  }),
  contractFromMetadata(ImageMd, {
    name: "Image",
    includeLayoutProps: true,
    eventAttributes: {
      click: "onClick",
    },
  }),
  contractFromMetadata(IFrameMd, {
    name: "IFrame",
    includeLayoutProps: true,
    eventAttributes: {
      load: "onLoad",
    },
  }),
  {
    name: "App",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true, global: true },
    props: withLayoutProps({
      testId: { name: "testId" },
      useHashBasedRouting: { name: "useHashBasedRouting" },
    }),
    events: {
      ready: { name: "ready", attributeName: "onReady" },
      messageReceived: { name: "messageReceived", attributeName: "onMessageReceived" },
      keyDown: { name: "keyDown", attributeName: "onKeyDown" },
      keyUp: { name: "keyUp", attributeName: "onKeyUp" },
    },
  },
  {
    name: "AppHeader",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps(),
    events: {},
  },
  {
    name: "Heading",
    kind: "builtin",
    acceptsArbitraryProps: true,
    allowsChildren: true,
    declarations: {},
    props: withLayoutProps({
      id: { name: "id" },
      value: { name: "value" },
      level: { name: "level" },
      maxLines: { name: "maxLines" },
      ellipses: { name: "ellipses" },
      preserveLinebreaks: { name: "preserveLinebreaks" },
      omitFromToc: { name: "omitFromToc" },
      showAnchor: { name: "showAnchor" },
      anchorId: { name: "anchorId" },
      anchorTemplate: { name: "anchorTemplate" },
      testId: { name: "testId" },
    }),
    events: {},
    templates: {
      anchorTemplate: { name: "anchorTemplate" },
    },
    contextVariables: {
      $anchorId: { name: "$anchorId" },
      $anchorHref: { name: "$anchorHref" },
    },
    apis: {
      scrollIntoView: { name: "scrollIntoView" },
      hasOverflow: { name: "hasOverflow" },
    },
  },
  ...["H1", "H2", "H3", "H4", "H5", "H6"].map((name): XmluiComponentContract => ({
    name,
    kind: "builtin",
    acceptsArbitraryProps: true,
    allowsChildren: true,
    declarations: {},
    props: withLayoutProps({
      id: { name: "id" },
      value: { name: "value" },
      level: { name: "level" },
      maxLines: { name: "maxLines" },
      ellipses: { name: "ellipses" },
      preserveLinebreaks: { name: "preserveLinebreaks" },
      omitFromToc: { name: "omitFromToc" },
      showAnchor: { name: "showAnchor" },
      anchorId: { name: "anchorId" },
      anchorTemplate: { name: "anchorTemplate" },
      testId: { name: "testId" },
    }),
    events: {},
    templates: {
      anchorTemplate: { name: "anchorTemplate" },
    },
    contextVariables: {
      $anchorId: { name: "$anchorId" },
      $anchorHref: { name: "$anchorHref" },
    },
    apis: {
      scrollIntoView: { name: "scrollIntoView" },
      hasOverflow: { name: "hasOverflow" },
    },
  })),
  {
    name: "Icon",
    kind: "builtin",
    allowsChildren: false,
    declarations: {},
    props: withLayoutProps({
      name: { name: "name" },
      testId: { name: "testId" },
    }),
    events: {},
  },
  {
    name: "Stack",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({ testId: { name: "testId" } }),
    events: {},
  },
  {
    name: "FlowLayout",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({ testId: { name: "testId" } }),
    events: {},
  },
  {
    name: "HStack",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({ testId: { name: "testId" } }),
    events: {},
  },
  {
    name: "VStack",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({ testId: { name: "testId" } }),
    events: {},
  },
  {
    name: "Button",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({
      autoFocus: { name: "autoFocus" },
      busyOnClick: { name: "busyOnClick" },
      contentPosition: { name: "contentPosition" },
      contextualLabel: { name: "contextualLabel" },
      label: { name: "label" },
      enabled: { name: "enabled" },
      icon: { name: "icon" },
      iconPosition: { name: "iconPosition" },
      orientation: { name: "orientation" },
      size: { name: "size" },
      testId: { name: "testId" },
      themeColor: { name: "themeColor" },
      type: { name: "type" },
      variant: { name: "variant" },
    }),
    events: {
      click: { name: "click", attributeName: "onClick" },
      contextMenu: { name: "contextMenu", attributeName: "onContextMenu" },
      gotFocus: { name: "gotFocus", attributeName: "onGotFocus" },
      lostFocus: { name: "lostFocus", attributeName: "onLostFocus" },
    },
  },
  {
    name: "Card",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({
      id: { name: "id" },
      avatarUrl: { name: "avatarUrl" },
      showAvatar: { name: "showAvatar" },
      avatarSize: { name: "avatarSize" },
      title: { name: "title" },
      subtitle: { name: "subtitle" },
      linkTo: { name: "linkTo" },
      orientation: { name: "orientation" },
      testId: { name: "testId" },
    }),
    events: {
      click: { name: "click", attributeName: "onClick" },
      doubleClick: { name: "doubleClick", attributeName: "onDoubleClick" },
      contextMenu: { name: "contextMenu", attributeName: "onContextMenu" },
    },
    apis: {
      scrollToTop: { name: "scrollToTop" },
      scrollToBottom: { name: "scrollToBottom" },
      scrollToLeft: { name: "scrollToLeft" },
      scrollToRight: { name: "scrollToRight" },
      scrollToStart: { name: "scrollToStart" },
      scrollToEnd: { name: "scrollToEnd" },
    },
  },
  {
    name: "Text",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({
      id: { name: "id" },
      value: { name: "value" },
      variant: { name: "variant" },
      maxLines: { name: "maxLines" },
      preserveLinebreaks: { name: "preserveLinebreaks" },
      ellipses: { name: "ellipses" },
      overflowMode: { name: "overflowMode" },
      breakMode: { name: "breakMode" },
      lang: { name: "lang" },
      testId: { name: "testId" },
    }),
    events: {
      contextMenu: { name: "contextMenu", attributeName: "onContextMenu" },
    },
    apis: {
      hasOverflow: { name: "hasOverflow" },
    },
  },
  {
    name: "Theme",
    kind: "builtin",
    acceptsArbitraryProps: true,
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps(),
    events: {},
  },
  {
    name: "Items",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({
      items: { name: "items" },
      data: { name: "data" },
      reverse: { name: "reverse" },
    }),
    events: {},
    templates: {
      itemTemplate: { name: "itemTemplate" },
    },
    contextVariables: {
      $item: { name: "$item" },
      $itemIndex: { name: "$itemIndex" },
      $isFirst: { name: "$isFirst" },
      $isLast: { name: "$isLast" },
    },
  },
  {
    name: "TextBox",
    kind: "builtin",
    allowsChildren: false,
    declarations: {},
    props: withLayoutProps({
      initialValue: { name: "initialValue" },
      placeholder: { name: "placeholder" },
      enabled: { name: "enabled" },
      readOnly: { name: "readOnly" },
      label: { name: "label" },
    }),
    events: {
      didChange: { name: "didChange", attributeName: "onDidChange" },
      gotFocus: { name: "gotFocus", attributeName: "onGotFocus" },
      lostFocus: { name: "lostFocus", attributeName: "onLostFocus" },
    },
  },
  {
    name: "Checkbox",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: withLayoutProps({
      initialValue: { name: "initialValue" },
      label: { name: "label" },
      enabled: { name: "enabled" },
      readOnly: { name: "readOnly" },
      indeterminate: { name: "indeterminate" },
    }),
    events: {
      click: { name: "click", attributeName: "onClick" },
      didChange: { name: "didChange", attributeName: "onDidChange" },
      gotFocus: { name: "gotFocus", attributeName: "onGotFocus" },
      lostFocus: { name: "lostFocus", attributeName: "onLostFocus" },
    },
  },
  {
    name: "Select",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: withLayoutProps({
      initialValue: { name: "initialValue" },
      value: { name: "value" },
      enabled: { name: "enabled" },
      readOnly: { name: "readOnly" },
      placeholder: { name: "placeholder" },
      label: { name: "label" },
      data: { name: "data" },
      valueField: { name: "valueField" },
      labelField: { name: "labelField" },
      multiSelect: { name: "multiSelect" },
      clearable: { name: "clearable" },
      searchable: { name: "searchable" },
    }),
    events: {
      didChange: { name: "didChange", attributeName: "onDidChange" },
      gotFocus: { name: "gotFocus", attributeName: "onGotFocus" },
      lostFocus: { name: "lostFocus", attributeName: "onLostFocus" },
    },
  },
  {
    name: "Option",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: {
      value: { name: "value" },
      label: { name: "label" },
      enabled: { name: "enabled" },
      keywords: { name: "keywords" },
    },
    events: {},
  },
  {
    name: "DataSource",
    kind: "builtin",
    allowsChildren: false,
    declarations: {},
    props: {
      id: { name: "id" },
      method: { name: "method" },
      url: { name: "url" },
      mockData: { name: "mockData" },
      body: { name: "body" },
      rawBody: { name: "rawBody" },
      queryParams: { name: "queryParams" },
      headers: { name: "headers" },
      credentials: { name: "credentials" },
      pollIntervalInSeconds: { name: "pollIntervalInSeconds" },
      resultSelector: { name: "resultSelector" },
      transformResult: { name: "transformResult" },
      dataType: { name: "dataType" },
      structuralSharing: { name: "structuralSharing" },
    },
    events: {
      loaded: { name: "loaded", attributeName: "onLoaded" },
      error: { name: "error", attributeName: "onError" },
      fetch: { name: "fetch", attributeName: "onFetch" },
    },
    contextVariables: {
      $url: { name: "$url" },
      $method: { name: "$method" },
      $queryParams: { name: "$queryParams" },
      $requestBody: { name: "$requestBody" },
      $requestHeaders: { name: "$requestHeaders" },
    },
    apis: {
      value: { name: "value" },
      inProgress: { name: "inProgress" },
      isRefetching: { name: "isRefetching" },
      loaded: { name: "loaded" },
      refetch: { name: "refetch" },
      responseHeaders: { name: "responseHeaders" },
    },
  },
  {
    name: "Pages",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({
      fallbackPath: { name: "fallbackPath" },
      defaultScrollRestoration: { name: "defaultScrollRestoration" },
    }),
    events: {},
  },
  {
    name: "Page",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: {
      url: { name: "url" },
      searchIndexable: { name: "searchIndexable" },
      navLabel: { name: "navLabel" },
      queryParams: { name: "queryParams" },
      guard: { name: "guard" },
    },
    events: {},
    contextVariables: {
      $pathname: { name: "$pathname" },
      $routeParams: { name: "$routeParams" },
      $queryParams: { name: "$queryParams" },
      $queryString: { name: "$queryString" },
    },
  },
  {
    name: "NavPanel",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps(),
    events: {},
  },
  {
    name: "NavLink",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({
      to: { name: "to" },
      enabled: { name: "enabled" },
      active: { name: "active" },
      target: { name: "target" },
      label: { name: "label" },
      vertical: { name: "vertical" },
      displayActive: { name: "displayActive" },
      noIndicator: { name: "noIndicator" },
      exact: { name: "exact" },
      icon: { name: "icon" },
      iconAlignment: { name: "iconAlignment" },
      level: { name: "level" },
    }),
    events: {
      click: { name: "click", attributeName: "onClick" },
    },
  },
  {
    name: "APICall",
    kind: "builtin",
    allowsChildren: false,
    declarations: {},
    props: {
      id: { name: "id" },
      method: { name: "method" },
      url: { name: "url" },
      body: { name: "body" },
      rawBody: { name: "rawBody" },
      queryParams: { name: "queryParams" },
      headers: { name: "headers" },
      credentials: { name: "credentials" },
      invalidates: { name: "invalidates" },
      updates: { name: "updates" },
    },
    events: {
      beforeRequest: { name: "beforeRequest", attributeName: "onBeforeRequest" },
      success: { name: "success", attributeName: "onSuccess" },
      error: { name: "error", attributeName: "onError" },
      mockExecute: { name: "mockExecute", attributeName: "onMockExecute" },
    },
    contextVariables: {
      $param: { name: "$param" },
      $params: { name: "$params" },
      $queryParams: { name: "$queryParams" },
      $requestBody: { name: "$requestBody" },
      $requestHeaders: { name: "$requestHeaders" },
    },
    apis: {
      execute: { name: "execute" },
      inProgress: { name: "inProgress" },
      loaded: { name: "loaded" },
      lastResult: { name: "lastResult" },
      lastError: { name: "lastError" },
      lastResponseHeaders: { name: "lastResponseHeaders" },
    },
  },
  {
    name: "Slot",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    acceptsArbitraryProps: true,
    props: {
      name: { name: "name" },
    },
    events: {},
  },
  {
    name: "property",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: {
      name: { name: "name" },
    },
    events: {},
  },
  {
    name: "method",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: {
      name: { name: "name" },
    },
    events: {},
  },
  {
    name: "Component",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: {
      name: { name: "name" },
    },
    events: {},
  },
];

function withLayoutProps(
  props: XmluiComponentContract["props"] = {},
): XmluiComponentContract["props"] {
  return {
    ...Object.fromEntries(
      supportedLayoutPropNames.map((name) => [name, { name }]),
    ),
    when: { name: "when" },
    ...props,
  };
}

export function normalizeEventName(attributeOrEventName: string): string {
  if (/^on[A-Z]/.test(attributeOrEventName)) {
    const eventName = attributeOrEventName.slice(2);
    return eventName.charAt(0).toLowerCase() + eventName.slice(1);
  }
  return attributeOrEventName;
}
