import type { XmluiComponentContract } from "./types";
import { supportedLayoutPropNames, supportedResponsiveLayoutPropNames } from "../../styling";
import { htmlTagDefinitions } from "../../component-core/htmlTags";
import { AccordionItemMd, AccordionMd } from "../../components/Accordion/Accordion";
import { ExpandableItemMd } from "../../components/ExpandableItem/ExpandableItem";
import { htmlTagMetadata } from "../../components/HtmlTags/HtmlTags";
import { BrCapitalizedMd, BrMd } from "../../components/Br/Br";
import { CardMd } from "../../components/Card/Card";
import { FragmentMd } from "../../components/Fragment/Fragment";
import { ImageMd } from "../../components/Image/Image";
import { IFrameMd } from "../../components/IFrame/IFrame";
import { LinkMd } from "../../components/Link/Link";
import { ItemsMd } from "../../components/Items/Items";
import { PasswordInputMd, TextBoxMd } from "../../components/TextBox/TextBox";
import { TextAreaMd } from "../../components/TextArea/TextArea";
import { NumberBoxMd } from "../../components/NumberBox/NumberBox";
import { RatingInputMd } from "../../components/RatingInput/RatingInput";
import { SliderMd } from "../../components/Slider/Slider";
import { ColorPickerMd } from "../../components/ColorPicker/ColorPicker";
import { DateInputMd } from "../../components/DateInput/DateInput";
import { DatePickerMd } from "../../components/DatePicker/DatePicker";
import { DrawerMd } from "../../components/Drawer/Drawer";
import { ModalDialogMd } from "../../components/ModalDialog/ModalDialog";
import { TooltipMd } from "../../components/Tooltip/Tooltip";
import { ContextMenuMd } from "../../components/ContextMenu/ContextMenu";
import { DropdownMenuMd, MenuItemMd, MenuSeparatorMd, SubMenuItemMd } from "../../components/DropdownMenu/DropdownMenu";
import { FileInputMd } from "../../components/FileInput/FileInput";
import { FileUploadDropZoneMd } from "../../components/FileUploadDropZone/FileUploadDropZone";
import { FlowLayoutMd } from "../../components/FlowLayout/FlowLayout";
import { ScrollViewerMd } from "../../components/ScrollViewer/ScrollViewer";
import { TimeInputMd } from "../../components/TimeInput/TimeInput";
import { TileGridMd } from "../../components/TileGrid/TileGrid";
import { ContentSeparatorMd } from "../../components/ContentSeparator/ContentSeparator";
import { FallbackMd } from "../../components/Fallback/Fallback";
import { NoResultMd } from "../../components/NoResult/NoResult";
import { PageMetaTitleMd } from "../../components/PageMetaTitle/PageMetaTitle";
import { QRCodeMd } from "../../components/QRCode/QRCode";
import { ResponsiveBarMd } from "../../components/ResponsiveBar/ResponsiveBar";
import { SpaceFillerMd } from "../../components/SpaceFiller/SpaceFiller";
import { HSplitterMd, SplitterMd, VSplitterMd } from "../../components/Splitter/Splitter";
import { StickyBoxMd } from "../../components/StickyBox/StickyBox";
import { StickySectionMd } from "../../components/StickySection/StickySection";
import { TabItemMd, TabsMd } from "../../components/Tabs/Tabs";
import { contractFromMetadata } from "./fromMetadata";

export const builtInComponentContracts: XmluiComponentContract[] = [
  ...htmlTagDefinitions.map((definition) =>
    contractFromMetadata(htmlTagMetadata[definition.name], {
      name: definition.name,
      acceptsArbitraryProps: true,
      includeLayoutProps: true,
    }),
  ),
  contractFromMetadata(BrMd, {
    name: "br",
    allowsChildren: false,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
  }),
  contractFromMetadata(BrCapitalizedMd, {
    name: "Br",
    allowsChildren: false,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
  }),
  contractFromMetadata(AccordionMd, {
    name: "Accordion",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      displayDidChange: "onDisplayDidChange",
    },
  }),
  contractFromMetadata(AccordionItemMd, {
    name: "AccordionItem",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
  }),
  contractFromMetadata(ExpandableItemMd, {
    name: "ExpandableItem",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      expandedChange: "onExpandedChange",
    },
  }),
  contractFromMetadata(TabsMd, {
    name: "Tabs",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      didChange: "onDidChange",
      contextMenu: "onContextMenu",
    },
  }),
  contractFromMetadata(TabItemMd, {
    name: "TabItem",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      activated: "onActivated",
    },
  }),
  contractFromMetadata(DrawerMd, {
    name: "Drawer",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      open: "onOpen",
      close: "onClose",
    },
  }),
  contractFromMetadata(ModalDialogMd, {
    name: "ModalDialog",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      open: "onOpen",
      close: "onClose",
    },
  }),
  contractFromMetadata(TooltipMd, {
    name: "Tooltip",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
  }),
  contractFromMetadata(ContextMenuMd, {
    name: "ContextMenu",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
  }),
  contractFromMetadata(DropdownMenuMd, {
    name: "DropdownMenu",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      willOpen: "onWillOpen",
    },
  }),
  contractFromMetadata(MenuItemMd, {
    name: "MenuItem",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      click: "onClick",
    },
  }),
  contractFromMetadata(MenuSeparatorMd, {
    name: "MenuSeparator",
    allowsChildren: false,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
  }),
  contractFromMetadata(SubMenuItemMd, {
    name: "SubMenuItem",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
  }),
  contractFromMetadata(FragmentMd, {
    name: "Fragment",
    includeLayoutProps: false,
  }),
  contractFromMetadata(ImageMd, {
    name: "Image",
    includeLayoutProps: true,
    eventAttributes: {
      click: "onClick",
    },
  }),
  contractFromMetadata(IFrameMd, {
    name: "IFrame",
    includeLayoutProps: true,
    eventAttributes: {
      load: "onLoad",
    },
  }),
  {
    name: "App",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true, global: true },
    props: withLayoutProps({
      testId: { name: "testId" },
      loggedInUser: { name: "loggedInUser" },
      useHashBasedRouting: { name: "useHashBasedRouting" },
      "backgroundColor-content-App": { name: "backgroundColor-content-App" },
      "borderLeft-content-App": { name: "borderLeft-content-App" },
      "maxWidth-content-App": { name: "maxWidth-content-App" },
      "paddingHorizontal-content-App": { name: "paddingHorizontal-content-App" },
      "paddingVertical-content-App": { name: "paddingVertical-content-App" },
      "gap-content-App": { name: "gap-content-App" },
    }),
    events: {
      ready: { name: "ready", attributeName: "onReady" },
      messageReceived: { name: "messageReceived", attributeName: "onMessageReceived" },
      keyDown: { name: "keyDown", attributeName: "onKeyDown" },
      keyUp: { name: "keyUp", attributeName: "onKeyUp" },
    },
  },
  {
    name: "AppHeader",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({
      profileMenuTemplate: { name: "profileMenuTemplate" },
      logoTemplate: { name: "logoTemplate" },
      titleTemplate: { name: "titleTemplate" },
      title: { name: "title" },
      showLogo: { name: "showLogo" },
      testId: { name: "testId" },
      id: { name: "id" },
    }),
    events: {},
  },
  {
    name: "Footer",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({
      sticky: { name: "sticky" },
      testId: { name: "testId" },
      id: { name: "id" },
    }),
    events: {},
  },
  {
    name: "Heading",
    kind: "builtin",
    acceptsArbitraryProps: true,
    allowsChildren: true,
    declarations: {},
    props: withLayoutProps({
      id: { name: "id" },
      value: { name: "value" },
      level: { name: "level" },
      maxLines: { name: "maxLines" },
      ellipses: { name: "ellipses" },
      preserveLinebreaks: { name: "preserveLinebreaks" },
      omitFromToc: { name: "omitFromToc" },
      showAnchor: { name: "showAnchor" },
      anchorId: { name: "anchorId" },
      anchorTemplate: { name: "anchorTemplate" },
      testId: { name: "testId" },
    }),
    events: {},
    templates: {
      anchorTemplate: { name: "anchorTemplate" },
    },
    contextVariables: {
      $anchorId: { name: "$anchorId" },
      $anchorHref: { name: "$anchorHref" },
    },
    apis: {
      scrollIntoView: { name: "scrollIntoView" },
      hasOverflow: { name: "hasOverflow" },
    },
  },
  ...["H1", "H2", "H3", "H4", "H5", "H6"].map((name): XmluiComponentContract => ({
    name,
    kind: "builtin",
    acceptsArbitraryProps: true,
    allowsChildren: true,
    declarations: {},
    props: withLayoutProps({
      id: { name: "id" },
      value: { name: "value" },
      level: { name: "level" },
      maxLines: { name: "maxLines" },
      ellipses: { name: "ellipses" },
      preserveLinebreaks: { name: "preserveLinebreaks" },
      omitFromToc: { name: "omitFromToc" },
      showAnchor: { name: "showAnchor" },
      anchorId: { name: "anchorId" },
      anchorTemplate: { name: "anchorTemplate" },
      testId: { name: "testId" },
    }),
    events: {},
    templates: {
      anchorTemplate: { name: "anchorTemplate" },
    },
    contextVariables: {
      $anchorId: { name: "$anchorId" },
      $anchorHref: { name: "$anchorHref" },
    },
    apis: {
      scrollIntoView: { name: "scrollIntoView" },
      hasOverflow: { name: "hasOverflow" },
    },
  })),
  {
    name: "Icon",
    kind: "builtin",
    allowsChildren: false,
    acceptsArbitraryProps: true,
    declarations: {},
    props: withLayoutProps({
      fallback: { name: "fallback" },
      name: { name: "name" },
      size: { name: "size" },
      testId: { name: "testId" },
    }),
    events: {
      click: { name: "click", attributeName: "onClick" },
    },
  },
  {
    name: "Logo",
    kind: "builtin",
    allowsChildren: false,
    declarations: {},
    props: withLayoutProps({
      src: { name: "src" },
      alt: { name: "alt" },
      inline: { name: "inline" },
      testId: { name: "testId" },
    }),
    events: {},
  },
  contractFromMetadata(PageMetaTitleMd, {
    name: "PageMetaTitle",
    allowsChildren: true,
    includeLayoutProps: false,
  }),
  contractFromMetadata(QRCodeMd, {
    name: "QRCode",
    allowsChildren: false,
    includeLayoutProps: true,
    eventAttributes: {
      init: "onInit",
    },
  }),
  contractFromMetadata(ContentSeparatorMd, {
    name: "ContentSeparator",
    allowsChildren: false,
    includeLayoutProps: true,
  }),
  contractFromMetadata(NoResultMd, {
    name: "NoResult",
    allowsChildren: true,
    includeLayoutProps: true,
  }),
  contractFromMetadata(FallbackMd, {
    name: "Fallback",
    allowsChildren: true,
    includeLayoutProps: false,
  }),
  contractFromMetadata(SpaceFillerMd, {
    name: "SpaceFiller",
    allowsChildren: false,
    includeLayoutProps: false,
    acceptsArbitraryProps: true,
  }),
  contractFromMetadata(LinkMd, {
    name: "Link",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      click: "onClick",
    },
  }),
  contractFromMetadata(TextBoxMd, {
    name: "TextBox",
    allowsChildren: false,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      didChange: "onDidChange",
      gotFocus: "onGotFocus",
      lostFocus: "onLostFocus",
    },
  }),
  contractFromMetadata(PasswordInputMd, {
    name: "PasswordInput",
    allowsChildren: false,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      didChange: "onDidChange",
      gotFocus: "onGotFocus",
      lostFocus: "onLostFocus",
    },
  }),
  contractFromMetadata(TextAreaMd, {
    name: "TextArea",
    allowsChildren: false,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      didChange: "onDidChange",
      gotFocus: "onGotFocus",
      lostFocus: "onLostFocus",
    },
  }),
  contractFromMetadata(NumberBoxMd, {
    name: "NumberBox",
    allowsChildren: false,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      didChange: "onDidChange",
      gotFocus: "onGotFocus",
      lostFocus: "onLostFocus",
    },
  }),
  contractFromMetadata(RatingInputMd, {
    name: "RatingInput",
    allowsChildren: false,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      didChange: "onDidChange",
      gotFocus: "onGotFocus",
      lostFocus: "onLostFocus",
    },
  }),
  contractFromMetadata(SliderMd, {
    name: "Slider",
    allowsChildren: false,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      didChange: "onDidChange",
      gotFocus: "onGotFocus",
      lostFocus: "onLostFocus",
    },
  }),
  contractFromMetadata(ColorPickerMd, {
    name: "ColorPicker",
    allowsChildren: false,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      didChange: "onDidChange",
      gotFocus: "onGotFocus",
      lostFocus: "onLostFocus",
    },
  }),
  contractFromMetadata(DateInputMd, {
    name: "DateInput",
    allowsChildren: false,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      didChange: "onDidChange",
      gotFocus: "onGotFocus",
      lostFocus: "onLostFocus",
    },
  }),
  contractFromMetadata(DatePickerMd, {
    name: "DatePicker",
    allowsChildren: false,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      didChange: "onDidChange",
      gotFocus: "onGotFocus",
      lostFocus: "onLostFocus",
    },
  }),
  contractFromMetadata(FileInputMd, {
    name: "FileInput",
    allowsChildren: false,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      didChange: "onDidChange",
      gotFocus: "onGotFocus",
      lostFocus: "onLostFocus",
      parseError: "onParseError",
    },
  }),
  contractFromMetadata(FileUploadDropZoneMd, {
    name: "FileUploadDropZone",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      upload: "onUpload",
    },
  }),
  contractFromMetadata(TileGridMd, {
    name: "TileGrid",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      selectionDidChange: "onSelectionDidChange",
      itemDoubleClick: "onItemDoubleClick",
      contextMenu: "onContextMenu",
    },
  }),
  contractFromMetadata(TimeInputMd, {
    name: "TimeInput",
    allowsChildren: false,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      didChange: "onDidChange",
      gotFocus: "onGotFocus",
      lostFocus: "onLostFocus",
      invalidTime: "onInvalidTime",
    },
  }),
  {
    name: "Stack",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps(stackProps()),
    events: stackEvents(),
  },
  contractFromMetadata(FlowLayoutMd, {
    name: "FlowLayout",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      contextMenu: "onContextMenu",
    },
  }),
  contractFromMetadata(ScrollViewerMd, {
    name: "ScrollViewer",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
  }),
  contractFromMetadata(ResponsiveBarMd, {
    name: "ResponsiveBar",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      click: "onClick",
      willOpen: "onWillOpen",
    },
  }),
  contractFromMetadata(SplitterMd, {
    name: "Splitter",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      resize: "onResize",
    },
  }),
  contractFromMetadata(HSplitterMd, {
    name: "HSplitter",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      resize: "onResize",
    },
  }),
  contractFromMetadata(VSplitterMd, {
    name: "VSplitter",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      resize: "onResize",
    },
  }),
  contractFromMetadata(StickyBoxMd, {
    name: "StickyBox",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
  }),
  contractFromMetadata(StickySectionMd, {
    name: "StickySection",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
  }),
  {
    name: "HStack",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps(stackProps()),
    events: stackEvents(),
  },
  {
    name: "VStack",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps(stackProps()),
    events: stackEvents(),
  },
  {
    name: "CodeBlock",
    kind: "builtin",
    acceptsArbitraryProps: true,
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({
      meta: { name: "meta" },
      testId: { name: "testId" },
    }),
    events: {},
  },
  {
    name: "Button",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({
      autoFocus: { name: "autoFocus" },
      busyOnClick: { name: "busyOnClick" },
      contentPosition: { name: "contentPosition" },
      contextualLabel: { name: "contextualLabel" },
      label: { name: "label" },
      enabled: { name: "enabled" },
      icon: { name: "icon" },
      iconPosition: { name: "iconPosition" },
      orientation: { name: "orientation" },
      size: { name: "size" },
      testId: { name: "testId" },
      themeColor: { name: "themeColor" },
      type: { name: "type" },
      variant: { name: "variant" },
    }),
    events: {
      click: { name: "click", attributeName: "onClick" },
      contextMenu: { name: "contextMenu", attributeName: "onContextMenu" },
      gotFocus: { name: "gotFocus", attributeName: "onGotFocus" },
      lostFocus: { name: "lostFocus", attributeName: "onLostFocus" },
    },
  },
  contractFromMetadata(CardMd, {
    name: "Card",
    allowsChildren: true,
    includeLayoutProps: true,
    acceptsArbitraryProps: true,
    eventAttributes: {
      click: "onClick",
      doubleClick: "onDoubleClick",
      contextMenu: "onContextMenu",
    },
  }),
  {
    name: "Text",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({
      id: { name: "id" },
      value: { name: "value" },
      variant: { name: "variant" },
      maxLines: { name: "maxLines" },
      preserveLinebreaks: { name: "preserveLinebreaks" },
      ellipses: { name: "ellipses" },
      overflowMode: { name: "overflowMode" },
      breakMode: { name: "breakMode" },
      lang: { name: "lang" },
      testId: { name: "testId" },
    }),
    events: {
      contextMenu: { name: "contextMenu", attributeName: "onContextMenu" },
    },
    apis: {
      hasOverflow: { name: "hasOverflow" },
    },
  },
  {
    name: "Theme",
    kind: "builtin",
    acceptsArbitraryProps: true,
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps(),
    events: {},
  },
  contractFromMetadata(ItemsMd, {
    name: "Items",
    allowsChildren: true,
    includeLayoutProps: false,
  }),
  {
    name: "Checkbox",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: withLayoutProps({
      id: { name: "id" },
      testId: { name: "testId" },
      initialValue: { name: "initialValue" },
      value: { name: "value" },
      label: { name: "label" },
      labelPosition: { name: "labelPosition" },
      labelBreak: { name: "labelBreak" },
      labelWidth: { name: "labelWidth" },
      direction: { name: "direction" },
      enabled: { name: "enabled" },
      readOnly: { name: "readOnly" },
      required: { name: "required" },
      autoFocus: { name: "autoFocus" },
      indeterminate: { name: "indeterminate" },
      validationStatus: { name: "validationStatus" },
      requireLabelMode: { name: "requireLabelMode" },
      bindTo: { name: "bindTo" },
      tooltip: { name: "tooltip" },
      tooltipMarkdown: { name: "tooltipMarkdown" },
      animation: { name: "animation" },
      variant: { name: "variant" },
    }),
    events: {
      click: { name: "click", attributeName: "onClick" },
      didChange: { name: "didChange", attributeName: "onDidChange" },
      gotFocus: { name: "gotFocus", attributeName: "onGotFocus" },
      lostFocus: { name: "lostFocus", attributeName: "onLostFocus" },
    },
  },
  {
    name: "Switch",
    kind: "builtin",
    allowsChildren: false,
    declarations: {},
    props: withLayoutProps({
      id: { name: "id" },
      testId: { name: "testId" },
      initialValue: { name: "initialValue" },
      value: { name: "value" },
      label: { name: "label" },
      labelPosition: { name: "labelPosition" },
      labelBreak: { name: "labelBreak" },
      labelWidth: { name: "labelWidth" },
      direction: { name: "direction" },
      enabled: { name: "enabled" },
      readOnly: { name: "readOnly" },
      required: { name: "required" },
      autoFocus: { name: "autoFocus" },
      validationStatus: { name: "validationStatus" },
      requireLabelMode: { name: "requireLabelMode" },
      bindTo: { name: "bindTo" },
      tooltip: { name: "tooltip" },
      tooltipMarkdown: { name: "tooltipMarkdown" },
      animation: { name: "animation" },
      variant: { name: "variant" },
    }),
    events: {
      click: { name: "click", attributeName: "onClick" },
      didChange: { name: "didChange", attributeName: "onDidChange" },
      gotFocus: { name: "gotFocus", attributeName: "onGotFocus" },
      lostFocus: { name: "lostFocus", attributeName: "onLostFocus" },
    },
  },
  {
    name: "Select",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: withLayoutProps({
      id: { name: "id" },
      testId: { name: "testId" },
      initialValue: { name: "initialValue" },
      value: { name: "value" },
      enabled: { name: "enabled" },
      readOnly: { name: "readOnly" },
      placeholder: { name: "placeholder" },
      label: { name: "label" },
      data: { name: "data" },
      valueField: { name: "valueField" },
      labelField: { name: "labelField" },
      multiSelect: { name: "multiSelect" },
      clearable: { name: "clearable" },
      searchable: { name: "searchable" },
    }),
    events: {
      didChange: { name: "didChange", attributeName: "onDidChange" },
      gotFocus: { name: "gotFocus", attributeName: "onGotFocus" },
      lostFocus: { name: "lostFocus", attributeName: "onLostFocus" },
    },
  },
  {
    name: "Option",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: {
      value: { name: "value" },
      label: { name: "label" },
      testId: { name: "testId" },
      enabled: { name: "enabled" },
      keywords: { name: "keywords" },
    },
    events: {},
  },
  {
    name: "RadioGroup",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: withLayoutProps({
      id: { name: "id" },
      testId: { name: "testId" },
      initialValue: { name: "initialValue" },
      value: { name: "value" },
      label: { name: "label" },
      labelPosition: { name: "labelPosition" },
      direction: { name: "direction" },
      autoFocus: { name: "autoFocus" },
      required: { name: "required" },
      readOnly: { name: "readOnly" },
      enabled: { name: "enabled" },
      validationStatus: { name: "validationStatus" },
      orientation: { name: "orientation" },
      gap: { name: "gap" },
    }),
    events: {
      didChange: { name: "didChange", attributeName: "onDidChange" },
      gotFocus: { name: "gotFocus", attributeName: "onGotFocus" },
      lostFocus: { name: "lostFocus", attributeName: "onLostFocus" },
    },
    apis: {
      value: { name: "value" },
      setValue: { name: "setValue" },
    },
  },
  {
    name: "AutoComplete",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: withLayoutProps({
      id: { name: "id" },
      testId: { name: "testId" },
      placeholder: { name: "placeholder" },
      initialValue: { name: "initialValue" },
      value: { name: "value" },
      maxLength: { name: "maxLength" },
      autoFocus: { name: "autoFocus" },
      required: { name: "required" },
      readOnly: { name: "readOnly" },
      enabled: { name: "enabled" },
      initiallyOpen: { name: "initiallyOpen" },
      creatable: { name: "creatable" },
      validationStatus: { name: "validationStatus" },
      dropdownHeight: { name: "dropdownHeight" },
      multi: { name: "multi" },
    }),
    events: {
      didChange: { name: "didChange", attributeName: "onDidChange" },
      gotFocus: { name: "gotFocus", attributeName: "onGotFocus" },
      lostFocus: { name: "lostFocus", attributeName: "onLostFocus" },
      itemCreated: { name: "itemCreated", attributeName: "onItemCreated" },
    },
  },
  {
    name: "Pagination",
    kind: "builtin",
    allowsChildren: false,
    declarations: { local: true },
    props: withLayoutProps({
      id: { name: "id" },
      testId: { name: "testId" },
      enabled: { name: "enabled" },
      itemCount: { name: "itemCount" },
      pageSize: { name: "pageSize" },
      pageIndex: { name: "pageIndex" },
      maxVisiblePages: { name: "maxVisiblePages" },
      showPageInfo: { name: "showPageInfo" },
      showPageSizeSelector: { name: "showPageSizeSelector" },
      showCurrentPage: { name: "showCurrentPage" },
      pageSizeOptions: { name: "pageSizeOptions" },
      hasPrevPage: { name: "hasPrevPage" },
      hasNextPage: { name: "hasNextPage" },
      orientation: { name: "orientation" },
      pageSizeSelectorPosition: { name: "pageSizeSelectorPosition" },
      pageInfoPosition: { name: "pageInfoPosition" },
      buttonRowPosition: { name: "buttonRowPosition" },
    }),
    events: {
      pageDidChange: { name: "pageDidChange", attributeName: "onPageDidChange" },
      pageSizeDidChange: { name: "pageSizeDidChange", attributeName: "onPageSizeDidChange" },
    },
    apis: {
      moveFirst: { name: "moveFirst" },
      moveLast: { name: "moveLast" },
      movePrev: { name: "movePrev" },
      moveNext: { name: "moveNext" },
      currentPage: { name: "currentPage" },
      currentPageSize: { name: "currentPageSize" },
    },
  },
  {
    name: "SelectionStore",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: {
      id: { name: "id" },
      idKey: { name: "idKey" },
      value: { name: "value" },
    },
    events: {},
  },
  {
    name: "List",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: withLayoutProps({
      id: { name: "id" },
      testId: { name: "testId" },
      data: { name: "data" },
      items: { name: "items" },
      loading: { name: "loading" },
      limit: { name: "limit" },
      groupBy: { name: "groupBy" },
      orderBy: { name: "orderBy" },
      itemTemplate: { name: "itemTemplate" },
      emptyListTemplate: { name: "emptyListTemplate" },
      groupHeaderTemplate: { name: "groupHeaderTemplate" },
      groupFooterTemplate: { name: "groupFooterTemplate" },
      idKey: { name: "idKey" },
      rowsSelectable: { name: "rowsSelectable" },
      enableMultiRowSelection: { name: "enableMultiRowSelection" },
      initiallySelected: { name: "initiallySelected" },
      hideSelectionCheckboxes: { name: "hideSelectionCheckboxes" },
    }),
    events: {
      contextMenu: { name: "contextMenu", attributeName: "onContextMenu" },
      rowDoubleClick: { name: "rowDoubleClick", attributeName: "onRowDoubleClick" },
      selectionDidChange: { name: "selectionDidChange", attributeName: "onSelectionDidChange" },
    },
  },
  {
    name: "Table",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: withLayoutProps({
      id: { name: "id" },
      testId: { name: "testId" },
      data: { name: "data" },
      items: { name: "items" },
      idKey: { name: "idKey" },
      isPaginated: { name: "isPaginated" },
      loading: { name: "loading" },
      rowsSelectable: { name: "rowsSelectable" },
      enableMultiRowSelection: { name: "enableMultiRowSelection" },
      initiallySelected: { name: "initiallySelected" },
      hideHeader: { name: "hideHeader" },
      hideSelectionCheckboxes: { name: "hideSelectionCheckboxes" },
      noDataTemplate: { name: "noDataTemplate" },
    }),
    events: {
      contextMenu: { name: "contextMenu", attributeName: "onContextMenu" },
      rowClick: { name: "rowClick", attributeName: "onRowClick" },
      rowDoubleClick: { name: "rowDoubleClick", attributeName: "onRowDoubleClick" },
      selectionDidChange: { name: "selectionDidChange", attributeName: "onSelectionDidChange" },
    },
    templates: {
      noDataTemplate: { name: "noDataTemplate" },
    },
    contextVariables: {
      $item: { name: "$item" },
      $itemIndex: { name: "$itemIndex" },
      $cell: { name: "$cell" },
      $colIndex: { name: "$colIndex" },
      $row: { name: "$row" },
      $rowIndex: { name: "$rowIndex" },
    },
    apis: {
      getSelectedIds: { name: "getSelectedIds" },
      getSelectedItems: { name: "getSelectedItems" },
      clearSelection: { name: "clearSelection" },
      selectAll: { name: "selectAll" },
    },
  },
  {
    name: "Column",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: {
      id: { name: "id" },
      bindTo: { name: "bindTo" },
      header: { name: "header" },
      width: { name: "width" },
      minWidth: { name: "minWidth" },
      maxWidth: { name: "maxWidth" },
      canSort: { name: "canSort" },
      pinTo: { name: "pinTo" },
      canResize: { name: "canResize" },
    },
    events: {},
    contextVariables: {
      $item: { name: "$item" },
      $cell: { name: "$cell" },
      $itemIndex: { name: "$itemIndex" },
      $colIndex: { name: "$colIndex" },
      $row: { name: "$row" },
      $rowIndex: { name: "$rowIndex" },
    },
  },
  {
    name: "Tree",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: withLayoutProps({
      id: { name: "id" },
      testId: { name: "testId" },
      data: { name: "data" },
      dataFormat: { name: "dataFormat" },
      idField: { name: "idField" },
      nameField: { name: "nameField" },
      parentIdField: { name: "parentIdField" },
      childrenField: { name: "childrenField" },
      selectableField: { name: "selectableField" },
      selectedValue: { name: "selectedValue" },
      selectedId: { name: "selectedId" },
      defaultExpanded: { name: "defaultExpanded" },
      itemClickExpands: { name: "itemClickExpands" },
      itemTemplate: { name: "itemTemplate" },
    }),
    events: {
      contextMenu: { name: "contextMenu", attributeName: "onContextMenu" },
      itemClick: { name: "itemClick", attributeName: "onItemClick" },
      selectionDidChange: { name: "selectionDidChange", attributeName: "onSelectionDidChange" },
    },
    templates: {
      itemTemplate: { name: "itemTemplate" },
    },
    contextVariables: {
      $item: { name: "$item" },
    },
    apis: {
      selectedId: { name: "selectedId" },
      expandAll: { name: "expandAll" },
      collapseAll: { name: "collapseAll" },
      selectId: { name: "selectId" },
    },
  },
  {
    name: "TreeDisplay",
    kind: "builtin",
    allowsChildren: false,
    declarations: {},
    props: withLayoutProps({
      testId: { name: "testId" },
      content: { name: "content" },
      itemHeight: { name: "itemHeight" },
    }),
    events: {
      contextMenu: { name: "contextMenu", attributeName: "onContextMenu" },
    },
  },
  {
    name: "TableOfContents",
    kind: "builtin",
    allowsChildren: false,
    declarations: {},
    props: withLayoutProps({
      testId: { name: "testId" },
      smoothScrolling: { name: "smoothScrolling" },
      maxHeadingLevel: { name: "maxHeadingLevel" },
      omitH1: { name: "omitH1" },
      scrollStyle: { name: "scrollStyle" },
      showScrollerFade: { name: "showScrollerFade" },
    }),
    events: {
      contextMenu: { name: "contextMenu", attributeName: "onContextMenu" },
    },
  },
  {
    name: "DataSource",
    kind: "builtin",
    allowsChildren: false,
    declarations: {},
    props: {
      id: { name: "id" },
      method: { name: "method" },
      url: { name: "url" },
      mockData: { name: "mockData" },
      body: { name: "body" },
      rawBody: { name: "rawBody" },
      queryParams: { name: "queryParams" },
      headers: { name: "headers" },
      credentials: { name: "credentials" },
      pollIntervalInSeconds: { name: "pollIntervalInSeconds" },
      resultSelector: { name: "resultSelector" },
      transformResult: { name: "transformResult" },
      dataType: { name: "dataType" },
      structuralSharing: { name: "structuralSharing" },
    },
    events: {
      loaded: { name: "loaded", attributeName: "onLoaded" },
      error: { name: "error", attributeName: "onError" },
      fetch: { name: "fetch", attributeName: "onFetch" },
    },
    contextVariables: {
      $url: { name: "$url" },
      $method: { name: "$method" },
      $queryParams: { name: "$queryParams" },
      $requestBody: { name: "$requestBody" },
      $requestHeaders: { name: "$requestHeaders" },
    },
    apis: {
      value: { name: "value" },
      inProgress: { name: "inProgress" },
      isRefetching: { name: "isRefetching" },
      loaded: { name: "loaded" },
      refetch: { name: "refetch" },
      responseHeaders: { name: "responseHeaders" },
    },
  },
  {
    name: "Pages",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({
      fallbackPath: { name: "fallbackPath" },
      defaultScrollRestoration: { name: "defaultScrollRestoration" },
    }),
    events: {},
  },
  {
    name: "Page",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: {
      url: { name: "url" },
      searchIndexable: { name: "searchIndexable" },
      navLabel: { name: "navLabel" },
      queryParams: { name: "queryParams" },
      guard: { name: "guard" },
    },
    events: {},
    contextVariables: {
      $pathname: { name: "$pathname" },
      $routeParams: { name: "$routeParams" },
      $queryParams: { name: "$queryParams" },
      $queryString: { name: "$queryString" },
    },
  },
  {
    name: "NavPanel",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({
      logoTemplate: { name: "logoTemplate" },
      footerTemplate: { name: "footerTemplate" },
      inDrawer: { name: "inDrawer" },
      scrollStyle: { name: "scrollStyle" },
      showScrollerFade: { name: "showScrollerFade" },
      syncWithContent: { name: "syncWithContent" },
      syncScrollBehavior: { name: "syncScrollBehavior" },
      syncScrollPosition: { name: "syncScrollPosition" },
      testId: { name: "testId" },
      id: { name: "id" },
    }),
    events: {},
  },
  {
    name: "NavLink",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({
      to: { name: "to" },
      enabled: { name: "enabled" },
      active: { name: "active" },
      target: { name: "target" },
      label: { name: "label" },
      vertical: { name: "vertical" },
      displayActive: { name: "displayActive" },
      noIndicator: { name: "noIndicator" },
      exact: { name: "exact" },
      icon: { name: "icon" },
      iconAlignment: { name: "iconAlignment" },
      level: { name: "level" },
      testId: { name: "testId" },
      id: { name: "id" },
    }),
    events: {
      click: { name: "click", attributeName: "onClick" },
    },
  },
  {
    name: "NavPanelCollapseButton",
    kind: "builtin",
    allowsChildren: false,
    declarations: {},
    props: withLayoutProps({
      icon: { name: "icon" },
      iconCollapsed: { name: "iconCollapsed" },
      "aria-label": { name: "aria-label" },
      "aria-labelCollapsed": { name: "aria-labelCollapsed" },
      testId: { name: "testId" },
      id: { name: "id" },
    }),
    events: {},
  },
  {
    name: "NavGroup",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: withLayoutProps({
      label: { name: "label" },
      initiallyExpanded: { name: "initiallyExpanded" },
      enabled: { name: "enabled" },
      to: { name: "to" },
      icon: { name: "icon" },
      iconHorizontalExpanded: { name: "iconHorizontalExpanded" },
      iconVerticalExpanded: { name: "iconVerticalExpanded" },
      iconHorizontalCollapsed: { name: "iconHorizontalCollapsed" },
      iconVerticalCollapsed: { name: "iconVerticalCollapsed" },
      noIndicator: { name: "noIndicator" },
      iconAlignment: { name: "iconAlignment" },
      expandIconAlignment: { name: "expandIconAlignment" },
      testId: { name: "testId" },
      id: { name: "id" },
    }),
    events: {},
  },
  {
    name: "APICall",
    kind: "builtin",
    allowsChildren: false,
    declarations: {},
    props: {
      id: { name: "id" },
      method: { name: "method" },
      url: { name: "url" },
      body: { name: "body" },
      rawBody: { name: "rawBody" },
      queryParams: { name: "queryParams" },
      headers: { name: "headers" },
      credentials: { name: "credentials" },
      invalidates: { name: "invalidates" },
      updates: { name: "updates" },
    },
    events: {
      beforeRequest: { name: "beforeRequest", attributeName: "onBeforeRequest" },
      success: { name: "success", attributeName: "onSuccess" },
      error: { name: "error", attributeName: "onError" },
      mockExecute: { name: "mockExecute", attributeName: "onMockExecute" },
    },
    contextVariables: {
      $param: { name: "$param" },
      $params: { name: "$params" },
      $queryParams: { name: "$queryParams" },
      $requestBody: { name: "$requestBody" },
      $requestHeaders: { name: "$requestHeaders" },
    },
    apis: {
      execute: { name: "execute" },
      inProgress: { name: "inProgress" },
      loaded: { name: "loaded" },
      lastResult: { name: "lastResult" },
      lastError: { name: "lastError" },
      lastResponseHeaders: { name: "lastResponseHeaders" },
    },
  },
  {
    name: "Slot",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    acceptsArbitraryProps: true,
    props: {
      name: { name: "name" },
    },
    events: {},
  },
  {
    name: "property",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: {
      name: { name: "name" },
    },
    events: {},
  },
  {
    name: "method",
    kind: "builtin",
    allowsChildren: true,
    declarations: {},
    props: {
      name: { name: "name" },
    },
    events: {},
  },
  {
    name: "Component",
    kind: "builtin",
    allowsChildren: true,
    declarations: { local: true },
    props: {
      name: { name: "name" },
    },
    events: {},
  },
];

function stackProps(): XmluiComponentContract["props"] {
  return {
    testId: { name: "testId" },
    desktopOnly: { name: "desktopOnly" },
    gap: { name: "gap" },
    reverse: { name: "reverse" },
    wrapContent: { name: "wrapContent" },
    orientation: { name: "orientation" },
    horizontalAlignment: { name: "horizontalAlignment" },
    verticalAlignment: { name: "verticalAlignment" },
    hoverContainer: { name: "hoverContainer" },
    visibleOnHover: { name: "visibleOnHover" },
    scrollStyle: { name: "scrollStyle" },
    showScrollerFade: { name: "showScrollerFade" },
    itemWidth: { name: "itemWidth" },
    dock: { name: "dock" },
  };
}

function stackEvents(): XmluiComponentContract["events"] {
  return {
    click: { name: "click", attributeName: "onClick" },
    contextMenu: { name: "contextMenu", attributeName: "onContextMenu" },
    mounted: { name: "mounted", attributeName: "onMounted" },
  };
}

function withLayoutProps(
  props: XmluiComponentContract["props"] = {},
): XmluiComponentContract["props"] {
  return {
    ...Object.fromEntries(
      supportedLayoutPropNames.map((name) => [name, { name }]),
    ),
    ...Object.fromEntries(
      supportedResponsiveLayoutPropNames.map((name) => [name, { name }]),
    ),
    when: { name: "when" },
    ...props,
  };
}

export function normalizeEventName(attributeOrEventName: string): string {
  if (/^on[A-Z]/.test(attributeOrEventName)) {
    const eventName = attributeOrEventName.slice(2);
    return eventName.charAt(0).toLowerCase() + eventName.slice(1);
  }
  return attributeOrEventName;
}
