export const ScriptTokenKind = {
  Unknown: "Unknown",
  EndOfFile: "EndOfFile",
  WhitespaceTrivia: "WhitespaceTrivia",
  NewLineTrivia: "NewLineTrivia",
  LineCommentTrivia: "LineCommentTrivia",
  BlockCommentTrivia: "BlockCommentTrivia",
  Identifier: "Identifier",
  NumberLiteral: "NumberLiteral",
  StringLiteral: "StringLiteral",
  TrueKeyword: "TrueKeyword",
  FalseKeyword: "FalseKeyword",
  NullKeyword: "NullKeyword",
  UndefinedKeyword: "UndefinedKeyword",
  LetKeyword: "LetKeyword",
  ConstKeyword: "ConstKeyword",
  IfKeyword: "IfKeyword",
  ElseKeyword: "ElseKeyword",
  WhileKeyword: "WhileKeyword",
  ForKeyword: "ForKeyword",
  Dollar: "Dollar",
  Dot: "Dot",
  OpenParen: "OpenParen",
  CloseParen: "CloseParen",
  OpenBracket: "OpenBracket",
  CloseBracket: "CloseBracket",
  OpenBrace: "OpenBrace",
  CloseBrace: "CloseBrace",
  Comma: "Comma",
  Semicolon: "Semicolon",
  Colon: "Colon",
  Question: "Question",
  QuestionDot: "QuestionDot",
  Arrow: "Arrow",
  LogicalOr: "LogicalOr",
  LogicalAnd: "LogicalAnd",
  NullishCoalescing: "NullishCoalescing",
  Exclamation: "Exclamation",
  Equal: "Equal",
  EqualEqual: "EqualEqual",
  EqualEqualEqual: "EqualEqualEqual",
  ExclamationEqual: "ExclamationEqual",
  ExclamationEqualEqual: "ExclamationEqualEqual",
  LessThan: "LessThan",
  LessThanEqual: "LessThanEqual",
  GreaterThan: "GreaterThan",
  GreaterThanEqual: "GreaterThanEqual",
  Plus: "Plus",
  Minus: "Minus",
  Star: "Star",
  Slash: "Slash",
  Percent: "Percent",
  PlusPlus: "PlusPlus",
  MinusMinus: "MinusMinus",
  PlusEqual: "PlusEqual",
  MinusEqual: "MinusEqual",
  StarEqual: "StarEqual",
  SlashEqual: "SlashEqual",
  PercentEqual: "PercentEqual",
} as const;

export type ScriptTokenKind = (typeof ScriptTokenKind)[keyof typeof ScriptTokenKind];

export function isScriptTrivia(kind: ScriptTokenKind): boolean {
  return (
    kind === ScriptTokenKind.WhitespaceTrivia ||
    kind === ScriptTokenKind.NewLineTrivia ||
    kind === ScriptTokenKind.LineCommentTrivia ||
    kind === ScriptTokenKind.BlockCommentTrivia
  );
}
