export const defaultProps = {
  idKey: "id",
  data: [] as unknown[],
  columns: [] as unknown[],
  isPaginated: false,
  loading: false,
  rowsSelectable: false,
  enableMultiRowSelection: true,
  toggleSelectionOnClick: false,
  initiallySelected: [] as unknown[],
  pageSizeOptions: [5, 10, 15],
  sortingDirection: "ascending" as "ascending" | "descending",
  autoFocus: false,
  hideHeader: false,
  hideNoDataView: false,
  hideSelectionCheckboxes: false,
  hideSelectionCheckboxesHeader: false,
  alwaysShowSelectionCheckboxesHeader: false,
  alwaysShowSelectionCheckboxes: false,
  alwaysShowSortingIndicator: false,
  noBottomBorder: false,
  paginationControlsLocation: "bottom" as "top" | "bottom" | "both",
  cellVerticalAlign: "center" as "top" | "center" | "bottom",
  showPageInfo: true,
  showPageSizeSelector: true,
  showCurrentPage: true,
  buttonRowPosition: "center" as "start" | "center" | "end",
  pageSizeSelectorPosition: "start" as "start" | "center" | "end",
  pageInfoPosition: "end" as "start" | "center" | "end",
  checkboxTolerance: "compact" as "none" | "compact" | "comfortable" | "spacious",
  rowHeight: 40,
  userSelectCell: "auto",
  userSelectRow: "auto",
  userSelectHeading: "none",
  alwaysShowHeader: false,
  striped: false,
};
