import { EMPTY_ARRAY } from "../../components-core/constants";
import type { CollectionDataRefreshMode } from "../../components-core/abstractions/dataRefreshAbstractions";

export const defaultProps = {
  idKey: "id",
  dataRefreshMode: "reset" as CollectionDataRefreshMode,
  data: EMPTY_ARRAY,
  columns: EMPTY_ARRAY,
  columnInference: "first-n(25)",
  columnSizing: "auto" as "auto" | "stretch" | "balanced" | "content",
  canResizeColumns: true,
  renderCache: true,
  renderCacheSize: 80,
  isPaginated: false,
  loading: false,
  loadingDelay: 400,
  rowsSelectable: false,
  enableMultiRowSelection: true,
  toggleSelectionOnClick: false,
  initiallySelected: EMPTY_ARRAY,
  pageSizeOptions: [5, 10, 15],
  sortingDirection: "ascending" as "ascending" | "descending",
  autoFocus: false,
  hideHeader: false,
  hideNoDataView: false,
  hideSelectionCheckboxes: false,
  hideSelectionCheckboxesHeader: false,
  alwaysShowSelectionCheckboxesHeader: false,
  alwaysShowSelectionCheckboxes: false,
  alwaysShowSortingIndicator: false,
  noBottomBorder: false,
  paginationControlsLocation: "bottom" as "top" | "bottom" | "both",
  cellVerticalAlign: "center" as "top" | "center" | "bottom",
  showPageInfo: true,
  showPageSizeSelector: true,
  showCurrentPage: true,
  buttonRowPosition: "center" as "start" | "center" | "end",
  pageSizeSelectorPosition: "start" as "start" | "center" | "end",
  pageInfoPosition: "end" as "start" | "center" | "end",
  checkboxTolerance: "compact" as "none" | "compact" | "comfortable" | "spacious",
  rowHeight: 40,
  userSelectCell: "auto",
  userSelectRow: "auto",
  userSelectHeading: "none",
  keyBindings: {
    selectAll: "CmdOrCtrl+A",
    cut: "CmdOrCtrl+X",
    copy: "CmdOrCtrl+C",
    paste: "CmdOrCtrl+V",
    delete: "Delete",
  },
  alwaysShowHeader: false,
  striped: false,
  highlightHoveredColumn: false,
};
