// Component chunk: stickybox
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { stickyBoxComponentRenderer } from "../components/StickyBox/StickyBox";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [stickyBoxComponentRenderer],
});
