// Component chunk: logo
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { logoComponentRenderer } from "../components/Logo/Logo";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [logoComponentRenderer],
});
