// Component chunk: accordionitem
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { accordionItemComponentRenderer } from "../components/Accordion/AccordionItem";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [accordionItemComponentRenderer],
});
