// Component chunk: markdown
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { markdownComponentRenderer } from "../components/Markdown/Markdown";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [markdownComponentRenderer],
});
