// Component chunk: blog
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { blogComponentRenderer } from "../components/Blog/Blog";
import { tableOfContentsRenderer } from "../components/TableOfContents/TableOfContents";
import { bookmarkComponentRenderer } from "../components/Bookmark/Bookmark";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [blogComponentRenderer, tableOfContentsRenderer, bookmarkComponentRenderer],
});
