// Component chunk: expandableitem
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { expandableItemComponentRenderer } from "../components/ExpandableItem/ExpandableItem";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [expandableItemComponentRenderer],
});
