// Component chunk: spacefiller
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { spaceFillerComponentRenderer } from "../components/SpaceFiller/SpaceFiller";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [spaceFillerComponentRenderer],
});
