// Component chunk: heading
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { headingComponentRenderer, h1ComponentRenderer, h2ComponentRenderer, h3ComponentRenderer, h4ComponentRenderer, h5ComponentRenderer, h6ComponentRenderer } from "../components/Heading/Heading";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [headingComponentRenderer, h1ComponentRenderer, h2ComponentRenderer, h3ComponentRenderer, h4ComponentRenderer, h5ComponentRenderer, h6ComponentRenderer],
});
