// Component chunk: contentseparator
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { contentSeparatorComponentRenderer } from "../components/ContentSeparator/ContentSeparator";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [contentSeparatorComponentRenderer],
});
