// Component chunk: codeeditor
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { codeEditorComponentRenderer } from "../components/CodeEditor/CodeEditorWrapped";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [codeEditorComponentRenderer],
});
