// Component chunk: slider
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { sliderComponentRenderer } from "../components/Slider/Slider";
import { sliderWrappedComponentRenderer } from "../components/Slider/SliderWrapped";
import { knobComponentRenderer } from "../components/Knob/KnobWrapped";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [sliderComponentRenderer, sliderWrappedComponentRenderer, knobComponentRenderer],
});
