// Component chunk: simpletooltip
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { tooltipComponentRenderer } from "../components/Tooltip/Tooltip";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [tooltipComponentRenderer],
});
