// Component chunk: tabitem
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { tabItemComponentRenderer } from "../components/Tabs/TabItem";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [tabItemComponentRenderer],
});
