// Component chunk: flowlayout
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { flowLayoutComponentRenderer } from "../components/FlowLayout/FlowLayout";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [flowLayoutComponentRenderer],
});
