// Component chunk: checkbox
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { checkboxComponentRenderer } from "../components/Checkbox/Checkbox";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [checkboxComponentRenderer],
});
