// Component chunk: fileuploaddropzone
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { fileUploadDropZoneComponentRenderer } from "../components/FileUploadDropZone/FileUploadDropZone";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [fileUploadDropZoneComponentRenderer],
});
