// Component chunk: image
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { imageComponentRenderer } from "../components/Image/Image";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [imageComponentRenderer],
});
