// Component chunk: selectionstore
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { selectionStoreComponentRenderer } from "../components/SelectionStore/SelectionStore";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [selectionStoreComponentRenderer],
});
