// Component chunk: qrcode
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { qrCodeComponentRenderer } from "../components/QRCode/QRCode";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [qrCodeComponentRenderer],
});
