// Component chunk: tree
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { treeComponentRenderer } from "../components/Tree/Tree";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [treeComponentRenderer],
});
