// Component chunk: text
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { textComponentRenderer } from "../components/Text/Text";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [textComponentRenderer],
});
