// Component chunk: messagelistener
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { messageListenerComponentRenderer } from "../components/MessageListener/MessageListener";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [messageListenerComponentRenderer],
});
