// Component chunk: navgroup
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { navGroupComponentRenderer } from "../components/NavGroup/NavGroup";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [navGroupComponentRenderer],
});
