// Component chunk: gauge
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { gaugeComponentRenderer } from "../components/Gauge/GaugeWrapped";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [gaugeComponentRenderer],
});
