// Component chunk: realtimeadapter
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { realTimeAdapterComponentRenderer } from "../components/RealTimeAdapter/RealTimeAdapter";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [realTimeAdapterComponentRenderer],
});
