// Component chunk: modaldialog
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { modalViewComponentRenderer } from "../components/ModalDialog/ModalDialog";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [modalViewComponentRenderer],
});
