// Component chunk: changelistener
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { changeListenerComponentRenderer } from "../components/ChangeListener/ChangeListener";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [changeListenerComponentRenderer],
});
