// Component chunk: radiogroup
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { radioGroupRenderer } from "../components/RadioGroup/RadioGroup";
import { radioItemComponentRenderer } from "../components/RadioGroup/RadioItem";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [radioGroupRenderer, radioItemComponentRenderer],
});
