// Component chunk: emojiselector
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { emojiSelectorRenderer } from "../components/EmojiSelector/EmojiSelector";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [emojiSelectorRenderer],
});
