// Component chunk: hovercard
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { hoverCardComponentRenderer } from "../components/HoverCard/HoverCard";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [hoverCardComponentRenderer],
});
