// Component chunk: datepicker
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { datePickerComponentRenderer } from "../components/DatePicker/DatePicker";
import { dateInputComponentRenderer } from "../components/DateInput/DateInput";
import { timeInputComponentRenderer } from "../components/TimeInput/TimeInput";
import { timerComponentRenderer } from "../components/Timer/Timer";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [datePickerComponentRenderer, dateInputComponentRenderer, timeInputComponentRenderer, timerComponentRenderer],
});
