// Component chunk: link
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { localLinkComponentRenderer } from "../components/Link/Link";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [localLinkComponentRenderer],
});
