// Component chunk: tabs
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { tabsComponentRenderer } from "../components/Tabs/Tabs";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [tabsComponentRenderer],
});
