// Component chunk: fileinput
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { fileInputRenderer } from "../components/FileInput/FileInput";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [fileInputRenderer],
});
