// Component chunk: select
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { selectComponentRenderer } from "../components/Select/Select";
import { autoCompleteComponentRenderer } from "../components/AutoComplete/AutoComplete";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [selectComponentRenderer, autoCompleteComponentRenderer],
});
