// Component chunk: echart
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { echartComponentRenderer } from "../components/EChart/EChartWrapped";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [echartComponentRenderer],
});
