// Component chunk: includemarkup
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { includeMarkupComponentRenderer } from "../components/IncludeMarkup/IncludeMarkup";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [includeMarkupComponentRenderer],
});
