// Component chunk: table
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { tableComponentRenderer } from "../components/Table/Table";
import { columnComponentRenderer } from "../components/Column/Column";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [tableComponentRenderer, columnComponentRenderer],
});
