// Component chunk: textarea
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { textAreaComponentRenderer } from "../components/TextArea/TextArea";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [textAreaComponentRenderer],
});
