// Component chunk: pagination
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { paginationComponentRenderer } from "../components/Pagination/Pagination";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [paginationComponentRenderer],
});
