// Component chunk: button
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { buttonComponentRenderer } from "../components/Button/Button";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [buttonComponentRenderer],
});
