// Component chunk: navpanel
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { navPanelRenderer } from "../components/NavPanel/NavPanel";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [navPanelRenderer],
});
