// Component chunk: toast
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { toastComponentRenderer } from "../components/Toast/Toast";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [toastComponentRenderer],
});
