// Component chunk: items
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { itemsComponentRenderer } from "../components/Items/Items";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [itemsComponentRenderer],
});
