// Component chunk: positionedcontainer
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { positionedContainerComponentRenderer } from "../components/PositionedContainer/PositionedContainer";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [positionedContainerComponentRenderer],
});
