// Component chunk: splitter
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { splitterComponentRenderer, vSplitterComponentRenderer, hSplitterComponentRenderer } from "../components/Splitter/Splitter";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [splitterComponentRenderer, vSplitterComponentRenderer, hSplitterComponentRenderer],
});
