// Component chunk: responsivebar
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { responsiveBarComponentRenderer } from "../components/ResponsiveBar/ResponsiveBar";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [responsiveBarComponentRenderer],
});
