// Component chunk: dropdownmenu
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { dropdownMenuComponentRenderer, menuItemRenderer, subMenuItemRenderer, menuSeparatorRenderer } from "../components/DropdownMenu/DropdownMenu";
import { contextMenuComponentRenderer } from "../components/ContextMenu/ContextMenu";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [dropdownMenuComponentRenderer, menuItemRenderer, subMenuItemRenderer, menuSeparatorRenderer, contextMenuComponentRenderer],
});
