// Component chunk: charts
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { areaChartComponentRenderer } from "../components/Charts/AreaChart/AreaChart";
import { barChartComponentRenderer } from "../components/Charts/BarChart/BarChart";
import { donutChartComponentRenderer } from "../components/Charts/DonutChart/DonutChart";
import { labelListComponentRenderer } from "../components/Charts/LabelList/LabelList";
import { legendComponentRenderer } from "../components/Charts/Legend/Legend";
import { lineChartComponentRenderer } from "../components/Charts/LineChart/LineChart";
import { pieChartComponentRenderer } from "../components/Charts/PieChart/PieChart";
import { radarChartComponentRenderer } from "../components/Charts/RadarChart/RadarChart";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [areaChartComponentRenderer, barChartComponentRenderer, donutChartComponentRenderer, labelListComponentRenderer, legendComponentRenderer, lineChartComponentRenderer, pieChartComponentRenderer, radarChartComponentRenderer],
});
