// Component chunk: badge
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { badgeComponentRenderer } from "../components/Badge/Badge";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [badgeComponentRenderer],
});
