// Component chunk: formsection
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { formSectionRenderer } from "../components/FormSection/FormSection";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [formSectionRenderer],
});
