// Component chunk: colorpicker
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { colorPickerComponentRenderer } from "../components/ColorPicker/ColorPicker";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [colorPickerComponentRenderer],
});
