// Component chunk: tonecontrols
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { toneChangerButtonComponentRenderer } from "../components/ToneChangerButton/ToneChangerButton";
import { navPanelCollapseButtonComponentRenderer } from "../components/NavPanelCollapseButton/NavPanelCollapseButton";
import { toneSwitchComponentRenderer } from "../components/ToneSwitch/ToneSwitch";
import { inspectButtonComponentRenderer } from "../components/InspectButton/InspectButton";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [toneChangerButtonComponentRenderer, navPanelCollapseButtonComponentRenderer, toneSwitchComponentRenderer, inspectButtonComponentRenderer],
});
