// Component chunk: carouselitem
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { carouselItemComponentRenderer } from "../components/Carousel/CarouselItem";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [carouselItemComponentRenderer],
});
