// Component chunk: accordion
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { accordionComponentRenderer } from "../components/Accordion/Accordion";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [accordionComponentRenderer],
});
