// Component chunk: scrollviewer
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { scrollViewerComponentRenderer } from "../components/ScrollViewer/ScrollViewer";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [scrollViewerComponentRenderer],
});
