// Component chunk: stack
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { stackComponentRenderer, vStackComponentRenderer, hStackComponentRenderer, cvStackComponentRenderer, chStackComponentRenderer } from "../components/Stack/Stack";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [stackComponentRenderer, vStackComponentRenderer, hStackComponentRenderer, cvStackComponentRenderer, chStackComponentRenderer],
});
