// Component chunk: queue
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { queueComponentRenderer } from "../components/Queue/Queue";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [queueComponentRenderer],
});
