// Component chunk: iframe
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { iframeComponentRenderer } from "../components/IFrame/IFrame";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [iframeComponentRenderer],
});
