// Component chunk: fragment
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { fragmentComponentRenderer } from "../components/Fragment/Fragment";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [fragmentComponentRenderer],
});
