// Component chunk: app
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { appRenderer } from "../components/App/App";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [appRenderer],
});
