// Component chunk: noresult
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { noResultComponentRenderer } from "../components/NoResult/NoResult";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [noResultComponentRenderer],
});
