// Component chunk: card
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { cardComponentRenderer } from "../components/Card/Card";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [cardComponentRenderer],
});
