// Component chunk: carousel
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { carouselComponentRenderer } from "../components/Carousel/Carousel";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [carouselComponentRenderer],
});
