// Component chunk: appheader
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { appHeaderComponentRenderer } from "../components/AppHeader/AppHeader";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [appHeaderComponentRenderer],
});
