// Component chunk: pages
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { pagesRenderer, pageRenderer } from "../components/Pages/Pages";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [pagesRenderer, pageRenderer],
});
