// Component chunk: footer
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { footerRenderer } from "../components/Footer/Footer";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [footerRenderer],
});
