// Component chunk: codeblock
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { codeBlockComponentRenderer } from "../components/CodeBlock/CodeBlock";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [codeBlockComponentRenderer],
});
