// Component chunk: tiptapeditor
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { tiptapEditorComponentRenderer } from "../components/TiptapEditor/TiptapEditorWrapped";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [tiptapEditorComponentRenderer],
});
