// Component chunk: icon
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { iconComponentRenderer } from "../components/Icon/Icon";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [iconComponentRenderer],
});
