// Component chunk: avatar
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { avatarComponentRenderer } from "../components/Avatar/Avatar";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [avatarComponentRenderer],
});
