// Component chunk: redirect
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { redirectRenderer } from "../components/Redirect/Redirect";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [redirectRenderer],
});
