// Component chunk: switch
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { switchComponentRenderer } from "../components/Switch/Switch";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [switchComponentRenderer],
});
