// Component chunk: backdrop
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { backdropComponentRenderer } from "../components/Backdrop/Backdrop";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [backdropComponentRenderer],
});
