// Component chunk: treedisplay
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { treeDisplayComponentRenderer } from "../components/TreeDisplay/TreeDisplay";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [treeDisplayComponentRenderer],
});
