// Component chunk: list
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { dynamicHeightListComponentRenderer } from "../components/List/List";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [dynamicHeightListComponentRenderer],
});
