// Component chunk: option
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { optionComponentRenderer } from "../components/Option/Option";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [optionComponentRenderer],
});
