// Component chunk: nestedapp
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { nestedAppComponentRenderer } from "../components/NestedApp/NestedApp";
import { appWithCodeViewComponentRenderer } from "../components/NestedApp/AppWithCodeView";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [nestedAppComponentRenderer, appWithCodeViewComponentRenderer],
});
