// Component chunk: progressbar
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { progressBarComponentRenderer } from "../components/ProgressBar/ProgressBar";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [progressBarComponentRenderer],
});
