// Component chunk: textbox
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { textBoxComponentRenderer, passwordInputComponentRenderer } from "../components/TextBox/TextBox";
import { numberBoxComponentRenderer } from "../components/NumberBox/NumberBox";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [textBoxComponentRenderer, passwordInputComponentRenderer, numberBoxComponentRenderer],
});
