// Component chunk: pagemetatitle
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { pageMetaTitleComponentRenderer } from "../components/PageMetaTitle/PageMetaTitle";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [pageMetaTitleComponentRenderer],
});
