// Component chunk: ratinginput
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { ratingInputComponentRenderer } from "../components/RatingInput/RatingInput";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [ratingInputComponentRenderer],
});
