// Component chunk: spinner
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { spinnerComponentRenderer } from "../components/Spinner/Spinner";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [spinnerComponentRenderer],
});
