// Component chunk: navlink
// Auto-generated by scripts/generate-chunk-entries.mjs
// Self-registers via the global Xmlui extension manager.
import { navLinkComponentRenderer } from "../components/NavLink/NavLink";

(window as any).Xmlui?.registerExtension({
  namespace: "#xmlui-core-ns",
  components: [navLinkComponentRenderer],
});
