import { expect, test } from "../../testing/fixtures";

// Regression: clicking a FormItem's label must focus the actual input element.
//
// Previously (see https://... label-click bug) the label's `htmlFor` attribute
// pointed to an id that was only generated by ItemWithLabel — but that id never
// reached the underlying DOM input when FormItem rendered its child through the
// CustomFormItem/xmlui renderChild path. So clicking the label did nothing.
//
// These tests verify that for every common FormItem usage pattern the label is
// wired to a focusable DOM element and clicking it focuses (or toggles) that
// element — no matter whether the input is declared as a `<FormItem type="...">`
// shorthand or as a nested child template `<FormItem><TextBox/></FormItem>`.

test.describe("FormItem label click focuses the input", () => {
  test("child-template TextBox", async ({ initTestBed, page }) => {
    await initTestBed(`
      <Form>
        <FormItem label="Name" bindTo="name">
          <TextBox />
        </FormItem>
      </Form>
    `);
    const label = page.locator("label", { hasText: "Name" });
    await expect(label).toHaveAttribute("for", /.+/);
    const forId = await label.getAttribute("for");
    const target = page.locator(`[id="${forId}"]`);
    await expect(target).toHaveCount(1);
    await label.click();
    await expect(target).toBeFocused();
  });

  test("child-template Select opens dropdown on label click", async ({
    initTestBed,
    page,
  }) => {
    await initTestBed(`
      <Form>
        <FormItem label="Pick" bindTo="pick">
          <Select>
            <Option label="A" value="a" />
            <Option label="B" value="b" />
          </Select>
        </FormItem>
      </Form>
    `);
    const label = page.locator("label", { hasText: "Pick" });
    const forId = await label.getAttribute("for");
    const trigger = page.locator(`[id="${forId}"]`);
    await expect(trigger).toHaveAttribute("aria-expanded", "false");
    await label.click();
    await expect(trigger).toHaveAttribute("aria-expanded", "true");
  });

  test("child-template NumberBox", async ({ initTestBed, page }) => {
    await initTestBed(`
      <Form>
        <FormItem label="Amount" bindTo="amt">
          <NumberBox />
        </FormItem>
      </Form>
    `);
    const label = page.locator("label", { hasText: "Amount" });
    const forId = await label.getAttribute("for");
    const target = page.locator(`[id="${forId}"]`);
    await label.click();
    await expect(target).toBeFocused();
  });

  test("child-template DatePicker opens calendar on label click", async ({
    initTestBed,
    page,
  }) => {
    await initTestBed(`
      <Form>
        <FormItem label="When" bindTo="when">
          <DatePicker />
        </FormItem>
      </Form>
    `);
    const label = page.locator("label", { hasText: "When" });
    const forId = await label.getAttribute("for");
    const trigger = page.locator(`[id="${forId}"]`);
    await expect(trigger).toHaveAttribute("aria-expanded", "false");
    await label.click();
    await expect(trigger).toHaveAttribute("aria-expanded", "true");
  });

  test("child-template TextArea", async ({ initTestBed, page }) => {
    await initTestBed(`
      <Form>
        <FormItem label="Notes" bindTo="notes">
          <TextArea />
        </FormItem>
      </Form>
    `);
    const label = page.locator("label", { hasText: "Notes" });
    const forId = await label.getAttribute("for");
    const target = page.locator(`[id="${forId}"]`);
    await expect(target).toHaveJSProperty("tagName", "TEXTAREA");
    await label.click();
    await expect(target).toBeFocused();
  });

  test("type=checkbox label click toggles the checkbox", async ({
    initTestBed,
    page,
  }) => {
    await initTestBed(`
      <Form>
        <FormItem label="Agree" bindTo="ok" type="checkbox" />
      </Form>
    `);
    const label = page.locator("label", { hasText: "Agree" });
    const forId = await label.getAttribute("for");
    const checkbox = page.locator(`[id="${forId}"]`);
    await expect(checkbox).not.toBeChecked();
    await label.click();
    await expect(checkbox).toBeChecked();
  });

  test("type=switch label click toggles the switch", async ({
    initTestBed,
    page,
  }) => {
    await initTestBed(`
      <Form>
        <FormItem label="Dark" bindTo="dark" type="switch" />
      </Form>
    `);
    const label = page.locator("label", { hasText: "Dark" });
    const forId = await label.getAttribute("for");
    const sw = page.locator(`[id="${forId}"]`);
    await expect(sw).not.toBeChecked();
    await label.click();
    await expect(sw).toBeChecked();
  });

  test("type=text (built-in, no child template) still works", async ({
    initTestBed,
    page,
  }) => {
    await initTestBed(`
      <Form>
        <FormItem label="Email" bindTo="email" type="text" />
      </Form>
    `);
    const label = page.locator("label", { hasText: "Email" });
    const forId = await label.getAttribute("for");
    const input = page.locator(`[id="${forId}"]`);
    await label.click();
    await expect(input).toBeFocused();
  });
});

// Same behavior must hold when the input is used directly inside a Form via
// bindTo (the FormBindingWrapper path) — no FormItem wrapper involved.
test.describe("bindTo on core component directly (no FormItem wrapper)", () => {
  test("TextBox bindTo + label", async ({ initTestBed, page }) => {
    await initTestBed(`
      <Form>
        <TextBox bindTo="name" label="Name" />
      </Form>
    `);
    const label = page.locator("label", { hasText: "Name" });
    const forId = await label.getAttribute("for");
    const input = page.locator(`[id="${forId}"]`);
    await expect(input).toHaveJSProperty("tagName", "INPUT");
    await label.click();
    await expect(input).toBeFocused();
  });

  test("Select bindTo + label opens dropdown", async ({ initTestBed, page }) => {
    await initTestBed(`
      <Form>
        <Select bindTo="pick" label="Pick">
          <Option label="A" value="a" />
          <Option label="B" value="b" />
        </Select>
      </Form>
    `);
    const label = page.locator("label", { hasText: "Pick" });
    const forId = await label.getAttribute("for");
    const trigger = page.locator(`[id="${forId}"]`);
    await expect(trigger).toHaveAttribute("aria-expanded", "false");
    await label.click();
    await expect(trigger).toHaveAttribute("aria-expanded", "true");
  });

  test("NumberBox bindTo + label", async ({ initTestBed, page }) => {
    await initTestBed(`
      <Form>
        <NumberBox bindTo="amt" label="Amount" />
      </Form>
    `);
    const label = page.locator("label", { hasText: "Amount" });
    const forId = await label.getAttribute("for");
    const input = page.locator(`[id="${forId}"]`);
    await label.click();
    await expect(input).toBeFocused();
  });

  test("DatePicker bindTo + label opens calendar", async ({
    initTestBed,
    page,
  }) => {
    await initTestBed(`
      <Form>
        <DatePicker bindTo="when" label="When" />
      </Form>
    `);
    const label = page.locator("label", { hasText: "When" });
    const forId = await label.getAttribute("for");
    const trigger = page.locator(`[id="${forId}"]`);
    await expect(trigger).toHaveAttribute("aria-expanded", "false");
    await label.click();
    await expect(trigger).toHaveAttribute("aria-expanded", "true");
  });

  test("TextArea bindTo + label", async ({ initTestBed, page }) => {
    await initTestBed(`
      <Form>
        <TextArea bindTo="notes" label="Notes" />
      </Form>
    `);
    const label = page.locator("label", { hasText: "Notes" });
    const forId = await label.getAttribute("for");
    const target = page.locator(`[id="${forId}"]`);
    await expect(target).toHaveJSProperty("tagName", "TEXTAREA");
    await label.click();
    await expect(target).toBeFocused();
  });

  test("Checkbox bindTo + label toggles the checkbox", async ({
    initTestBed,
    page,
  }) => {
    await initTestBed(`
      <Form>
        <Checkbox bindTo="ok" label="Agree" />
      </Form>
    `);
    const label = page.locator("label", { hasText: "Agree" });
    const forId = await label.getAttribute("for");
    const checkbox = page.locator(`[id="${forId}"]`);
    await expect(checkbox).not.toBeChecked();
    await label.click();
    await expect(checkbox).toBeChecked();
  });

  test("Switch bindTo + label toggles the switch", async ({
    initTestBed,
    page,
  }) => {
    await initTestBed(`
      <Form>
        <Switch bindTo="dark" label="Dark" />
      </Form>
    `);
    const label = page.locator("label", { hasText: "Dark" });
    const forId = await label.getAttribute("for");
    const sw = page.locator(`[id="${forId}"]`);
    await expect(sw).not.toBeChecked();
    await label.click();
    await expect(sw).toBeChecked();
  });
});
