import "./global.css";

export {
  createXmluiModule,
  mountXmluiApp,
  renderXmluiApp,
  startApp,
  XmluiRoot,
  type MountXmluiAppOptions,
  type XmluiDocumentInput,
  type XmluiModule,
} from "./runtime";
export type { ApiInterceptorDefinition } from "./components-core/interception/abstractions";
export {
  createComponentRenderer,
  createMetadata,
  createUserDefinedComponentRenderer,
  COMPONENT_PART_KEY,
  Button,
  dClick,
  dComponent,
  dDidChange,
  dEnabled,
  dGotFocus,
  dInitialValue,
  dLostFocus,
  FlowItemWrapper,
  FlowLayout,
  Heading,
  Icon,
  Image,
  LinkNative,
  Markdown,
  parseScssVar,
  Part,
  SEARCH_CATEGORIES,
  SEARCH_DEFAULT_CATEGORY,
  TabItem,
  TableOfContents,
  Tabs,
  Text,
  TextBox,
  Theme,
  useAppContext,
  useComponentThemeClass,
  useLinkInfo,
  useSearchContextContent,
  useTheme,
  VisuallyHidden,
  wrapComponent,
  wrapCompound,
  type ComponentMetadata,
  type CompoundComponentRendererInfo,
  type NavHierarchyNode,
  type PropertyValueDescription,
  type RegisterComponentApiFn,
} from "./extensionAuthoringCompat";
export {
  StandaloneExtensionManager,
  extensionComponentNames,
  globalExtensionManager,
  listRegisteredExtensions,
  normalizeExtensions,
  registerExtension,
  type ComponentExtension,
  type Extension,
  type ExtensionRegisteredCallback,
  type ThemeDefinition,
  type XmluiExtensionComponent,
  type XmluiExtensionComponentProps,
} from "./extensions";
