/**
 * Global state factory for compiled XMLUI apps.
 * Replaces the deprecated AppState bucket store with React Context + useReducer.
 * The compiler generates one GlobalStateProvider per root globalVars declaration.
 */

import { createContext, useContext, useReducer, type Dispatch, type ReactNode } from "react";

export type GlobalAction =
  | { type: "SET"; key: string; value: unknown }
  | { type: "MERGE"; patch: Record<string, unknown> };

function globalReducer(state: Record<string, unknown>, action: GlobalAction): Record<string, unknown> {
  switch (action.type) {
    case "SET":
      return { ...state, [action.key]: action.value };
    case "MERGE":
      return { ...state, ...action.patch };
    default:
      return state;
  }
}

export interface GlobalStateProviderResult<T extends Record<string, unknown>> {
  /** Wrap your app in this provider */
  Provider: ({ children, initialState }: { children: ReactNode; initialState?: Partial<T> }) => JSX.Element;
  /** Read the current global state */
  useGlobalState: () => T;
  /** Get a dispatch function to mutate global state */
  useGlobalDispatch: () => Dispatch<GlobalAction>;
}

/**
 * createGlobalStateProvider<T>(defaultState)
 *
 * Usage — generated by the compiler for each globalVars block:
 *   const { Provider, useGlobalState, useGlobalDispatch } =
 *     createGlobalStateProvider({ count: 0, user: null });
 */
export function createGlobalStateProvider<T extends Record<string, unknown>>(
  defaultState: T,
): GlobalStateProviderResult<T> {
  const StateContext = createContext<T>(defaultState);
  const DispatchContext = createContext<Dispatch<GlobalAction>>(() => {});

  function Provider({ children, initialState }: { children: ReactNode; initialState?: Partial<T> }) {
    const [state, dispatch] = useReducer(globalReducer, { ...defaultState, ...initialState } as Record<string, unknown>);
    return (
      <StateContext.Provider value={state as T}>
        <DispatchContext.Provider value={dispatch}>{children}</DispatchContext.Provider>
      </StateContext.Provider>
    );
  }

  return {
    Provider,
    useGlobalState: () => useContext(StateContext),
    useGlobalDispatch: () => useContext(DispatchContext),
  };
}
