import type { TreeDataFormat, DefaultExpansion } from "../../components-core/abstractions/treeAbstractions";

export const defaultProps = {
  dataFormat: "flat" as TreeDataFormat,
  idField: "id",
  nameField: "name",
  iconField: "icon",
  iconExpandedField: "iconExpanded",
  iconCollapsedField: "iconCollapsed",
  parentIdField: "parentId",
  childrenField: "children",
  selectableField: "selectable",
  defaultExpanded: "none" as DefaultExpansion,
  autoExpandToSelection: true,
  itemClickExpands: false,
  dynamicField: "dynamic",
  loadedField: "loaded",
  autoLoadAfterField: "autoLoadAfter",
  dynamic: false,
  iconCollapsed: "chevronright",
  iconExpanded: "chevrondown",
  iconSize: "16",
  itemHeight: 32,
  animateExpand: false,
  expandRotation: 90,
  scrollStyle: "normal" as "normal" | "overlay" | "whenMouseOver" | "whenScrolling",
  showScrollerFade: false,
  autoLoadAfter: undefined as number | undefined,
  spinnerDelay: 0,
};
