export const defaultProps = {
  dataFormat: "flat" as "flat" | "hierarchy",
  idField: "id",
  nameField: "name",
  iconField: "icon",
  iconExpandedField: "iconExpanded",
  iconCollapsedField: "iconCollapsed",
  parentIdField: "parentId",
  childrenField: "children",
  selectableField: "selectable",
  selectedValue: undefined as unknown,
  selectedId: undefined as unknown,
  defaultExpanded: "none" as "none" | "all" | "first-level" | unknown[],
  autoExpandToSelection: true,
  itemClickExpands: false,
  iconCollapsed: "chevronright",
  iconExpanded: "chevrondown",
  iconSize: "16",
  itemHeight: 32,
  fixedItemSize: false,
  animateExpand: false,
  expandRotation: 90,
  scrollStyle: "normal" as "normal" | "overlay" | "whenMouseOver" | "whenScrolling",
  showScrollerFade: false,
  dynamicField: "dynamic",
  loadedField: "loaded",
  autoLoadAfterField: "autoLoadAfter",
  dynamic: false,
  autoLoadAfter: undefined as number | undefined,
  spinnerDelay: 0,
};
