export const defaultProps = {
  enabled: true,
  validationStatus: "none",
  mode: "single",
  dateFormat: "MM/dd/yyyy",
  inline: false,
  clearable: false,
  weekStartsOn: 0,
  showWeekNumber: false,
  showWeekNumbers: false,
  locale: "en-US",
  timeZone: "UTC",
  numOfMonths: 1,
  showPresets: false,
  confirmRangeSelection: false,
  required: false,
  readOnly: false,
  autoFocus: false,
};
