// Export icon names for documentation purposes
export const ICON_NAMES = {
  ASSIGN: "assign",
  ARROW_UP: "arrowup",
  ARROW_LEFT: "arrowleft",
  ARROW_RIGHT: "arrowright",
  ARROW_DOWN: "arrowdown",
  PAUSE: "pause",
  PLAY: "play",
  DATE: "date",
  HAMBURGER: "hamburger",
  SEND: "send",
  USERS: "users",
  REFRESH: "refresh",
  CHEVRON_DOWN: "chevrondown",
  CHEVRON_UP: "chevronup",
  CHEVRON_RIGHT: "chevronright",
  CHEVRON_LEFT: "chevronleft",
  CHEVRONS_RIGHT: "chevronsright",
  CHEVRONS_LEFT: "chevronsleft",
  DOUBLE_CHEVRON_DOWN: "doublechevrondown",
  DOUBLE_CHEVRON_UP: "doublechevronup",
  DOUBLE_CHEVRON_RIGHT: "doublechevronright",
  DOUBLE_CHEVRON_LEFT: "doublechevronleft",
  DOT_MENU: "dotmenu",
  DOT_MENU_HORIZONTAL: "dotmenuhorizontal",
  NO_RESULT: "noresult",
  CRM: "crm",
  CHAT: "chat",
  PENCIL: "pencil",
  CUBE: "cube",
  APPS: "apps",
  PERMISSIONS: "permissions",
  CLOSE: "close",
  STAR: "star",
  HELP: "help",
  COMPACT_LIST: "compactlist",
  COPY: "copy",
  MOVE: "move",
  RENAME: "rename",
  HYPERLINK: "hyperlink",
  GLOBE: "globe",
  LINK: "link",
  LOOSE_LIST: "looselist",
  OPTIONS: "options",
  SEARCH: "search",
  FILTER: "filter",
  TRASH: "trash",
  PEN: "pen",
  EMAIL: "email",
  PHONE: "phone",
  HOME: "home",
  USER: "user",
  EXIT: "exit",
  ADD_USER: "adduser",
  USER_MINUS: "userminus",
  PLUS: "plus",
  INSPECT: "inspect",
  PLUS_CIRCLE: "plus-circle",
  FILLED_PLUS: "filledplus",
  DARK_TO_LIGHT: "darktolight",
  LIGHT_TO_DARK: "lighttodark",
  CHECKMARK: "checkmark",
  VALID: "valid",
  INFO: "info",
  ERROR: "error",
  WARNING: "warning",
  BOARD: "board",
  LIST: "list",
  FOLDER: "folder",
  FOLDER_OUTLINE: "folder-outline",
  EMPTY_FOLDER: "emptyfolder",
  PDF: "pdf",
  TXT: "txt",
  DOC: "doc",
  DOCX: "docx",
  DOC_OUTLINE: "doc-outline",
  CONF: "conf",
  CODE: "code",
  CODE_SANDBOX: "codesandbox",
  BOX: "box",
  XLS: ["xls", "xlsx"],
  IMAGE_FILES: ["jpg", "jpeg", "png", "webp", "svg", "gif", "tif", "ppt", "pptx"],
  UNKNOWN_FILE: "unknownfile",
  PHOTO: "photo",
  PREVIOUS: "previous",
  NEXT: "next",
  LIKE: "like",
  REPLY: "reply",
  ATTACH: "attach",
  ATTACH2: "attach2",
  EMOJI: "emoji",
  MESSAGE: "message",
  UPLOAD: "upload",
  SPLIT_VERTICAL: "split-vertical",
  SPLIT_HORIZONTAL: "split-horizontal",
  SWAP: "swap",
  DOWNLOAD: "download",
  NOTE: "note",
  BINDING: "binding",
  DATABASE: "database",
  UNLINK: "unlink",
  API: "api",
  EXPRESSION: "expression",
  HASH: "hash",
  DRIVE: "drive",
  LOCK: "lock",
  START: "start",
  STOP: "stop",
  RESTART: "restart",
  DUPLICATE: "duplicate",
  CONNECT: "connect",
  COG: "cog",
  SUN: "sun",
  MOON: "moon",
  STARS: "stars",
  SHARE: "share",
  NEW_WINDOW: "new-window",
  PAINT: "paint",
  PALETTE: "palette",
  TRENDING_UP: "trending-up",
  TRENDING_DOWN: "trending-down",
  TRENDING_LEVEL: "trending-level",
  SORT_ASC: "sortasc",
  SORT_DESC: "sortdesc",
  NO_SORT: "nosort",
  ADMONITION_INFO: "admonition_info",
  ADMONITION_WARNING: "admonition_warning",
  ADMONITION_DANGER: "admonition_danger",
  ADMONITION_NOTE: "admonition_note",
  ADMONITION_TIP: "admonition_tip",
  SQUARE: "square",
  SQUARE_HALF: "squarehalf",
  SQUARE_FILL: "squarefill",
  TABLE_INSERT_ROW: "table-insert-row",
  TABLE_DELETE_ROW: "table-delete-row",
  TABLE_INSERT_COLUMN: "table-insert-column",
  TABLE_DELETE_COLUMN: "table-delete-column",
  EYE: "eye",
  EYE_OFF: "eye-off",
} as const;

// Helper to get all icon names as a flat array
export function getAllIconNames(): string[] {
  const names: string[] = [];
  Object.values(ICON_NAMES).forEach((value) => {
    if (Array.isArray(value)) {
      names.push(...value);
    } else {
      names.push(value as string);
    }
  });
  return names;
}
