// We need these keys for extracting layout parameters
export const layoutOptionKeys = [
  "horizontalAlignment",
  "verticalAlignment",
  "orientation",
  "width",
  "minWidth",
  "maxWidth",
  "height",
  "minHeight",
  "maxHeight",
  "gap",
  "border",
  "borderTop",
  "borderRight",
  "borderBottom",
  "borderLeft",
  "borderColor",
  "borderStyle",
  "borderWidth",
  "borderHorizontal",
  "borderVertical",
  "borderRadius",
  "radiusTopLeft",
  "radiusTopRight",
  "radiusBottomLeft",
  "radiusBottomRight",
  "padding",
  "paddingHorizontal",
  "paddingVertical",
  "paddingTop",
  "paddingRight",
  "paddingBottom",
  "paddingLeft",
  "backgroundColor",
  "background",
  "boxShadow",
  "direction",
  "overflowX",
  "overflowY",
  "zIndex",
  "scrollSnapType",
  "scrollSnapAlign",
  "scrollSnapStop",
  "scrollPadding",
  "scrollPaddingTop",
  "scrollPaddingRight",
  "scrollPaddingBottom",
  "scrollPaddingLeft",
  "scrollMargin",
  "scrollMarginTop",
  "scrollMarginRight",
  "scrollMarginBottom",
  "scrollMarginLeft",
  "color",
  "fontFamily",
  "fontSize",
  "fontWeight",
  "fontStyle",
  "textDecoration",
  "wrapContent",
  "canShrink",
  "margin",
  "marginHorizontal",
  "marginVertical",
  "marginTop",
  "marginRight",
  "marginBottom",
  "marginLeft",
  "userSelect",
  "letterSpacing",
  "textTransform",
  "lineHeight",
  "opacity",
  "cursor",
  "textWrap",
  "textAlign",
  "textAlignLast",
  "top",
  "right",
  "bottom",
  "left",
  "zoom",
  "whiteSpace",
  "textDecoration",
  "textDecorationLine",
  "textDecorationColor",
  "textDecorationStyle",
  "textDecorationThickness",
  "textUnderlineOffset",
  "outline",
  "outlineWidth",
  "outlineColor",
  "outlineStyle",
  "outlineOffset",
  "fontVariant",
  "lineBreak",
  "textIndent",
  "textShadow",
  "wordBreak",
  "wordSpacing",
  "wordWrap",
  "writingMode",
  "transition",
  "transform",
];

/**
 * All property names contributed by built-in behaviors (trigger props + declared
 * props from every behavior). Safe to import anywhere — no React/component imports.
 * Keep in sync with the metadata defined in each behavior file under behaviors/.
 */
export const behaviorPropKeys: readonly string[] = [
  // AnimationBehavior — triggerProps: animation
  "animation", "animationOptions",
  // BookmarkBehavior — triggerProps: bookmark
  "bookmark", "bookmarkLevel", "bookmarkTitle", "bookmarkOmitFromToc",
  // FormBindingBehavior — triggerProps: bindTo
  "bindTo", "initialValue", "noSubmit",
  // LabelBehavior — triggerProps: label
  "label", "labelPosition", "labelWidth", "labelBreak",
  "required", "enabled", "shrinkToLabel", "style", "readOnly",
  // PubSubBehavior — triggerProps: subscribeToTopic
  "subscribeToTopic",
  // TooltipBehavior — triggerProps: tooltip, tooltipMarkdown
  "tooltip", "tooltipMarkdown", "tooltipOptions",
  // ValidationBehavior — triggerProps: bindTo
  "requiredInvalidMessage",
  "minLength", "maxLength", "lengthInvalidMessage", "lengthInvalidSeverity",
  "minValue", "maxValue", "rangeInvalidMessage", "rangeInvalidSeverity",
  "pattern", "patternInvalidMessage", "patternInvalidSeverity",
  "regex", "regexInvalidMessage", "regexInvalidSeverity",
  "validationMode", "verboseValidationFeedback",
  // VariantBehavior — triggerProps: variant
  "variant",
  // EXPERIMENTAL: universal prop to bypass event propagation stop for specific events
  "bubbleEvents",
];
