name: Chat CI/CD

on:
  push:
    paths:
      - client/packages/ChatEngine/**
      - client/packages/ui-engine/**
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      # checkout the repo
      - name: 'Checkout Github Action'
        uses: actions/checkout@v3

      - name: cache node modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install client
        run: npm i
        working-directory: client

      - name: npm install chat
        run: npm i
        working-directory: client/packages/ChatEngine
        
      - name: build chat package
        shell: bash
        run: npm run release-ci
        working-directory: client/packages/ChatEngine
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with:
          package: "client/packages/ChatEngine/ui.zip"
          app-name: chatengine
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_CHAT }}
