name: Component e2e nightly tests

concurrency: # Concurrency ensures that only a single job or workflow using the same concurrency group will run at a time.
  group: component-e2e-testing-nightly
  cancel-in-progress: true

on:
  schedule:
    # From the github docs:
    # "High load times include the start of every hour. If the load is sufficiently high enough, some queued jobs may be dropped. To decrease the chance of delay, schedule your workflow to run at a different time of the hour."
    # So this is kind of a random value
    - cron: "5 * * * *"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: ${{ steps.check-needs-to-run.outputs.shoud-run }}
    steps:
      - uses: actions/checkout@v3
      - name: check if job needs to run (commit is less than 23h old)
        id: check-needs-to-run
        run:
          if test $(( $(date +%s) - $(git show -s --format=%ct ${{ github.sha }}) )) -le 82800; then
          echo "::set-output name=shoud-run::true";
          else
          echo "::set-output name=shoud-run::false";
          fi
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: cache node modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install node dependencies
        run: npm ci
      - name: Store Playwright's Version
        working-directory: xmlui
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//' | sort | head -n 1)
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
      - name: Cache Playwright Browsers for Playwright's Version
        id: cache-playwright-browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
      - name: build test bed
        working-directory: xmlui
        run: npm run build:test-bed
      - name: Install Playwright Browsers
        working-directory: xmlui
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: xmlui
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: xmlui/playwright-report/
          retention-days: 30
