name: XMLUI Documentation CI/CD

on:
  workflow_dispatch:
  push:
    paths:
      - docs/**
    branches: [ captaaint/revert-extensions ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout Github Action'
        uses: actions/checkout@v3

      - name: cache node modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install
        run: npm i

      - name: npm install @napi-rs
        run: npm i @napi-rs/simple-git-linux-x64-gnu
        working-directory: docs

      - name: npm install docs
        run: npm i
        working-directory: docs

      - name: build docs package
        shell: bash
        run: npm run release-ci
        working-directory: docs

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with:
          package: "docs/ui.zip"
          app-name: xmlui-docs
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_XMLUI_DOCS }}
