name: XMLUI Documentation CI/CD

on:
  workflow_dispatch:
  push:
    paths:
      # - docs/**
    branches:
      # - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          registry-url: https://registry.npmjs.org/

      - run: npm ci --prefer-offline

      - run: npm run build
        working-directory: packages/xmlui-charts

      - run: npm run build
        working-directory: packages/xmlui-animations

      - run: npm run build
        working-directory: packages/xmlui-pdf

      - run: npm run build
        working-directory: packages/xmlui-devtools

      - name: build docs package
        run: npm run release-ci
        working-directory: docs

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with:
          package: "docs/ui.zip"
          app-name: xmlui-docs
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_XMLUI_DOCS }}
