name: Prepare versions for release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  create_version_pr:
    name: Create Stable Version PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --prefer-offline

      - name: Extract Pending Changes
        id: extract_changes
        run: |
          # Extract pending changes from .changeset files
          if [ -d .changeset ]; then
            CHANGES=$(find .changeset -name "*.md" -not -name "README.md" -exec cat {} \; | grep -v "^---" | grep -v "^$" | sort -u)
            echo "changes<<EOF" >> $GITHUB_ENV
            echo "$CHANGES" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            
            echo "Found pending changes in changesets:"
            echo "$CHANGES"
          else
            echo "No .changeset directory found"
          fi

      - name: Create Version PR
        id: changesets_pr
        uses: changesets/action@v1
        with:
          # Command to run for versioning.
          version: npm run changeset:version
          commit: 'chore: version packages for stable release'
          title: 'Version Packages for Stable Release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enhance PR Description with Changes
        if: steps.changesets_pr.outputs.pullRequestUrl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(echo "${{ steps.changesets_pr.outputs.pullRequestUrl }}" | awk -F/ '{print $NF}')
          
          # Get current PR description
          PR_DESCRIPTION=$(gh pr view $PR_NUMBER --json body -q .body)
          
          # Get the changes found earlier
          CHANGES='${{ env.changes }}'
          
          if [ ! -z "$CHANGES" ]; then
            # Create a file with the new description to avoid shell escaping issues
            cat > pr_description.md << EOL
          $PR_DESCRIPTION

          ### Detailed Changes
          $CHANGES
          EOL
            
            # Update PR description using the file
            gh pr edit $PR_NUMBER --body-file pr_description.md
            
            echo "Enhanced PR description with detailed changes"
          else
            echo "No changes to add to PR description"
          fi