name: Prepare versions for release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  create_version_pr:
    name: Create Stable Version PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --prefer-offline

      - name: Create Version PR
        id: changesets_pr
        uses: changesets/action@v1
        with:
          # Command to run for versioning.
          version: npm run changeset:version
          commit: 'chore: version packages for stable release'
          title: 'Version Packages for Stable Release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output Changeset PR URL
        if: steps.changesets_pr.outputs.pullRequestUrl
        run: |
          echo "Version PR created: ${{ steps.changesets_pr.outputs.pullRequestUrl }}"