name: Publish create-xmlui-app npm package

on:
  workflow_dispatch:

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 16
#      - run: npm ci
#        working-directory: client/packages/dummy-pkg
#      - run: npm test
#        working-directory: client/packages/dummy-pkg

  publish-gpr:
#    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        working-directory: tools/create-app
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_NPM_TOKEN}}