name: Run tests

concurrency:  # Concurrency ensures that only a single job or workflow using the same concurrency group will run at a time.
  group: integration-testing
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
env:
  DOTNET_VERSION: '6.0.x'
  NODE_VERSION: '18.x'
  
jobs:
  client-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: cache node modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: npm install client
        run: npm install

      - name: npm install common package
        run: npm install
        working-directory: packages/xmlui-engine  
        
      - name: run tests in common package
        run: npm run test
        working-directory: packages/xmlui-engine          