
name: Update Openapi Specification

on:
  pull_request:
    types: 
      - synchronize
      - opened
    paths:
      - CrmEngine.ClientApi/**
    branches:
      - master
        
env:
  DOTNET_VERSION: '6.0.x'
  
jobs:
  update-openapi-spec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CrmEngine.ClientApi
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore
        
      - name: Prepare tool-registy file
        run: dotnet new tool-manifest
        
      - name: Install tools
        run: dotnet tool install Swashbuckle.AspNetCore.Cli --version 6.3.1

      - name: Build
        run: dotnet build --no-restore 

      - name: Generate OpenApi spec file into /docs/swagger/swagger.json
        run: dotnet tool run swagger tofile --output ../docs/swagger/swagger.json ./bin/Debug/net6.0/CrmEngine.ClientApi.dll v1
        
      - name: Commit OpenApi specfile
        id: commit
        shell: bash
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if [ -z "$(git status --porcelain)" ]; then
            echo "::set-output name=push::false"
          else
            git commit -m "auto-generate swagger.json" -a
            echo "::set-output name=push::true"
          fi  

      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }}
