export const appContextObjectContract = {
  version: undefined,
  Actions: undefined,
  apiInterceptorContext: undefined,
  appGlobals: undefined,
  xmluiConfig: undefined,
  debugEnabled: undefined,
  decorateComponentsWithTestId: undefined,
  environment: undefined,
  mediaSize: undefined,
  queryClient: undefined,
  standalone: undefined,
  appIsInShadowDom: undefined,
  formatDate: undefined,
  formatDateTime: undefined,
  formatDateWithoutYear: undefined,
  formatTime: undefined,
  formatTimeWithoutSeconds: undefined,
  getDate: undefined,
  getDateUntilNow: undefined,
  isoDateString: undefined,
  isToday: undefined,
  isTomorrow: undefined,
  isYesterday: undefined,
  isSameDay: undefined,
  isThisYear: undefined,
  smartFormatDate: undefined,
  smartFormatDateTime: undefined,
  differenceInMinutes: undefined,
  formatHumanElapsedTime: undefined,
  avg: undefined,
  sum: undefined,
  formatFileSizeInBytes: undefined,
  getFileExtension: undefined,
  navigate: undefined,
  routerBaseName: undefined,
  pathname: undefined,
  setNavigationHandlers: undefined,
  confirm: undefined,
  signError: undefined,
  toast: undefined,
  activeThemeId: undefined,
  activeThemeTone: undefined,
  availableThemeIds: undefined,
  setTheme: undefined,
  setThemeTone: undefined,
  toggleThemeTone: undefined,
  getThemeVar: undefined,
  loggedInUser: undefined,
  setLoggedInUser: undefined,
  resources: undefined,
  capitalize: undefined,
  pluralize: undefined,
  delay: undefined,
  debounce: undefined,
  toHashObject: undefined,
  findByField: undefined,
  embed: undefined,
  distinct: undefined,
  forceRefreshAnchorScroll: undefined,
  scrollBookmarkIntoView: undefined,
  readLocalStorage: undefined,
  writeLocalStorage: undefined,
  deleteLocalStorage: undefined,
  clearLocalStorage: undefined,
  resetLocalStorage: undefined,
  getAllLocalStorage: undefined,
  storageTimestamp: undefined,
  AppState: undefined,
  Log: undefined,
  App: undefined,
  Clipboard: undefined,
  pubSubService: undefined,
  publishTopic: undefined,
} satisfies Record<string, undefined>;

export type AppContextObject = Record<keyof typeof appContextObjectContract, unknown> & {
  [x: string]: unknown;
};

export function isAppContextObjectProperty(name: string): name is keyof typeof appContextObjectContract {
  return Object.prototype.hasOwnProperty.call(appContextObjectContract, name);
}
